#!/bin/bash

AUTHORS="Lydia Iglesias, Narciso M. Quijada, Andrés Clemente-Blanco"
LASTMODIF="2026-05-17"
VERSION="0.4"
MODIFICATIONS="alignments with MATaVN"


DiGRAPH=$0
while [ -h "$DiGRAPH" ]; do # resolve $DiGRAPH until the file is no longer a symlink
  DiGRAPHDIR="$( cd -P "$( dirname "$0" )" && pwd )"
  DiGRAPH="$(readlink "$DiGRAPH")"
  [[ $DiGRAPH != /* ]] && DiGRAPH="$DiGRAPHDIR/$DiGRAPH" # if $DiGRAPH is a symlink, resolve it relative to the path where the symlink file was located
done
DiGRAPHDIR="$( cd -P "$( dirname "$DiGRAPH" )" && pwd )"

# WORKING VARIABLES
CATEGORY_PATH=
MYBLAST=
MYREF=
MYREPORT=
MYWD=
MYSCRIPTS=
STRAIN_REF="no"
NUMBER_EXP=3
N_CPU=$(nproc)
#N_CPU=$(sysctl -n hw.ncpu) #macOS

current_time=
log_file=
stats=

#MYREF=/home/ibfg/GWSL/RG # Replace with the path to your MYREF directory: path/to/RG
#MYWD=/home/ibfg/GWSL/WD/ # Replace with the path to your MYWD directory: path/to/WD
#CATEGORY_PATH=/home/ibfg/GWSL/Categories # Replace with the path to your CATEGORY_PATH directory: path/to/Categories
#MYBLAST=/home/ibfg/GWSL/BLAST/features_extraction # Replace with the path to your MYBLAST directory: path/to/BLAST
#MYREPORT=/home/ibfg/GWSL/Report_files # Replace with the path to your MYREPORT directory: path/to/Report_files

# Message colors
COL_RESET=$(tput sgr 0)
COL_blue=$(tput setaf 4)
COL_cyan=$(tput setaf 6)
COL_green=$(tput setaf 2)
COL_magenta=$(tput setaf 5)
COL_purple=$(tput setaf 5)
COL_red=$(tput setaf 1)
COL_white=$(tput setaf 7)
COL_yellow=$(tput setaf 3)

usage () {

cat << EOF

=============================================================

██████╗               ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗
██╔══██╗  ██╗        ██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║
██║  ██║  ╚═╝  ███╗  ██║  ███╗██████╔╝███████║██████╔╝███████║  
██║  ██║  ██╗  ╚══╝  ██║   ██║██╔╚██╗ ██╔══██║██╔═══╝ ██╔══██║  
██████╔╝  ██║        ╚██████╔╝██║ ╚██╗██║  ██║██║     ██║  ██║
╚═════╝   ╚═╝         ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝

      DSB-induced Genome-wide Repair Analysis 
     and Profiling of Homologous recombination
                   ${VERSION}
 ${AUTHORS}
=============================================================

Description:
This tool performs genome-wide analysis of DNA repair following an HO-induced break. 
Di-GRAPH integrates:
  - MAT repair profiling
  - Genome instability evaluation based on coverage 
  - Recombination analysis based on inter-chromosomal discordant reads
Input files are gzipped paired-end fastq files.

OBLIGATORY OPTIONS:
    -b/--blast          Path to BLAST genomic database for cross-validation directory (provided in GitHub)
    -c/--categories     Path to genomic categories and features annotation directory (provided in GitHub)
    -g/--genome         Path to reference genome directory (provided in GitHub)
    -i/--input          Path to input directory (working directory generated by the user)
    -r/--report         Path to report directory (provided in GitHub)
    -S/--scripts        Path to scripts directory (provided in GitHub)


OTHER OPTIONS:
    -h/--help           Shows this help
    -s/--strain_ref     Name of the strain to be used as a reference (example: 1_Wt)
    -n/--number_exp     Number of experiments (default=3)
    -t/--threads        Number of threads to use (default=${N_CPU})
    -v/--version        Show version

EOF
}

if [ $# == 0 ]; then
	usage
	exit 1
fi

# VARIABLE OPTIONS

POSITIONAL=()
while [[ $# -gt 0 ]]
do
ARGS="$1"

case $ARGS in
    -b|--blast)
    if [ "$2" ]; then
        MYBLAST=$2
        shift 2
        if [ ! -d "${MYBLAST}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYBLAST})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-b/--blast" requires an argument\n'
        exit 1
    fi
    ;;
    -c|--categories)
    if [ "$2" ]; then
        CATEGORY_PATH=$2
        shift 2
        if [ ! -d "${CATEGORY_PATH}" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${CATEGORY_PATH})" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-c/--categories" requires an argument\n'
        exit 1
    fi
    ;;
    -i|--input)
    if [ "$2" ]; then
        MYWD=$2
        shift 2
        if [ ! -d "${MYWD}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYWD})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-i/--input" requires an argument\n'
        exit 1
    fi
    ;;
    -g|--genome)
    if [ "$2" ]; then
        MYREF=$2
        shift 2
        if [ ! -d "${MYREF}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREF})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-g/--genome" requires an argument\n'
        exit 1
    fi
    ;;
    -r|--report)
    if [ "$2" ]; then
        MYREPORT=$2
        shift 2
        if [ ! -d "${MYREPORT}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREPORT})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -S|--scripts)
    if [ "$2" ]; then
        MYSCRIPTS=$2
        shift 2
        if [ ! -d "${MYSCRIPTS}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYSCRIPTS})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-R/--Rscripts" requires an argument\n'
        exit 1
    fi
    ;;
    -s|--strain_ref)
    if [ "$2" ]; then
        STRAIN_REF=$2
        #echo STRAIN_REF=$STRAIN_REF
        shift 2
        if [[ ! -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_red}ERROR: ${STRAIN_REF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [[ -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_cyan}REFERENCE STRAIN: ${STRAIN_REF} will be used as reference strain!${COL_RESET} \n"
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -n|--number_exp)
    if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NUMBER_EXP=$2
            shift 2
        else
            echo -e '\nERROR: "-n/--number_exp" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-n/--number_exp" requires a numeric argument\n'
        exit 1
    fi
    ;;
    -t|--threads)
	if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NCPUS=$2
            shift 2
        else
            echo -e '\nERROR: "-t/--threads" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-t/--threads" requires a numeric argument\n'
        exit 1
    fi
	;;
    -v|--version)
        echo "${COL_yellow}Di-GRAPH version ${VERSION}${COL_RESET}"
        exit 1
    ;;
    -h|--help)
	    usage
	    exit 1
	;;
    -?*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
	    exit 1
	;;
	*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
        exit 1
    ;;
esac
done
set -- "${POSITIONAL[@]}" #restore positional parameters


REQUIRED_VARS=(MYBLAST CATEGORY_PATH MYWD MYREF MYREPORT MYSCRIPTS)
REQUIRED_OPTS=(
  "-b/--blast"
  "-c/--categories"
  "-i/--input"
  "-g/--genome"
  "-r/--report"
  "-S/--scripts"
)

missing=0

for i in "${!REQUIRED_VARS[@]}"; do
    var="${REQUIRED_VARS[$i]}"
    opt="${REQUIRED_OPTS[$i]}"

    if [ -z "${!var}" ]; then
        echo -e "${COL_red}ERROR:${COL_RESET} Required option $opt is missing"
        missing=1
    fi
done

if [ "$missing" -eq 1 ]; then
    usage
    exit 1
fi

if [[ "$STRAIN_REF" == "no" ]]; then
    echo -e "\n${COL_blue}REFERENCE STRAIN: no reference strain will be used${COL_RESET} \n"
fi

if [[ "$NUMBER_EXP" != 3 ]]; then
    echo -e "\n${COL_blue}NUMBER OF EXPERIMENTS: $NUMBER_EXP experiments will be analyzed${COL_RESET} \n"
fi

read -rp "Please, enter experiment names (comma-separated, e.g. E1,E3,E4): " NAME_EXP

IFS=',' read -ra EXP_LIST <<< "$NAME_EXP"


if [ "${#EXP_LIST[@]}" -ne "$NUMBER_EXP" ]; then
    echo "ERROR: You specified $NUMBER_EXP experiments but provided ${#EXP_LIST[@]} names."
    exit 1
fi
#echo "Working"
#################################

######## Starting the analysis ########
# Create a log and stat file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
log_file="${MYWD}/log_file.txt"
stats="${MYWD}/stats.txt"

# Start timer for the entire script processing
start_time_total_script=$SECONDS

echo "CONCORDANT ANALYSIS FOR MATa and MATa' regions - initiated at: \"$current_time\"" > "$log_file"
echo "" >> "$log_file"  # Adds a blank line

# Index RG
bowtie-build "${MYREF}/RG_PMV_III_V_v9.fasta" "${MYREF}/S_cerevisiae_indexed_original" 
bowtie-build "${MYREF}/RG_PMV_III_MATaVN_v9 .fasta" "${MYREF}/S_cerevisiae_indexed_MATaVN" 

###########################################
### COVERAGE AND POLYMORPHISMS ANALYSIS ###
###########################################

echo "Coverage and Polymorphisms Analysis - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line

# Start timers for Coverage and Polymorphism Analysis processing

start_time_total_cov=$SECONDS

# Loop through each directory inside MYWD
for subdir in "$MYWD"*/; do
  echo "Processing directory: $subdir" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    for sample in T0 TSG TLG TLR; do
      for experiment in "${EXP_LIST[@]}"; do
        file1_gz="${subdir}/${sample}_${experiment}_R1.fastq.gz"
        file2_gz="${subdir}/${sample}_${experiment}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz" >> "$log_file"
          echo "" >> "$log_file"  # Adds a blank line

          # Decompress the current pair
          gunzip -k "$file1_gz" "$file2_gz"
          file1_path="${subdir}/${sample}_${experiment}_R1.fastq"
          file2_path="${subdir}/${sample}_${experiment}_R2.fastq"
          
          # Concatenate the two fastq files
          cat "$file1_path" "$file2_path" > "${subdir}/${sample}_${experiment}.fastq"
                
          # Remove original fastq files
          rm "$file1_path" "$file2_path"

          if [[ -f "${subdir}/${sample}_${experiment}.fastq" ]]; then
    
            # Trim reads using cutadapt
            cutadapt -j "$N_CPU" --cut -75 -o "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${subdir}/${sample}_${experiment}_2.fastq" "${subdir}/${sample}_${experiment}.fastq"

            # Remove intermediate fastq files
            rm "${subdir}/${sample}_${experiment}.fastq"

            # Concatenate processed 75nt reads into a single fastq file
            cat "${subdir}/${sample}_${experiment}_1.fastq" \
                "${subdir}/${sample}_${experiment}_2.fastq" \
              > "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq"
                    
                # Filter 75nt reads Q30
                fastp \
                  -i "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" \
                  -o "${subdir}/${sample}_${experiment}_75nt.fastq" \
                  -q 30 -u 0 -e 30 \
                  --thread "$N_CPU" \
                  --html "${subdir}/${sample}_${experiment}_75nt.fastq.html" \
                  --json "${subdir}/${sample}_${experiment}_75nt.fastq.json"
                rm "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" # Remove intermediate 75nt fastq files
                
            # Remove intermediate 75nt fastq files
            rm "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            
            # Bowtie mapping with original RG
            echo "### $(basename "$subdir")/${sample}/${experiment} 75nt original RG###" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed_original" "${subdir}/${sample}_${experiment}_75nt.fastq" > "${subdir}/${sample}_${experiment}_75nt_original.sam" 2>> "$stats"
            echo "" >> "$stats"

            # Bowtie mapping with MATaVN RG
            echo "### $(basename "$subdir")/${sample}/${experiment} 75nt MATaVN RG###" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed_MATaVN" "${subdir}/${sample}_${experiment}_75nt.fastq" > "${subdir}/${sample}_${experiment}_75nt_MATaVN.sam" 2>> "$stats"
            echo "" >> "$stats"
                    
            

            

            # Extract CHRIII and CHRV, remove columnes 2, 3, 5, 6, and add coordinates to the last column (75nt)
            for chr in CHRIII CHRV; do
              awk -F'\t' -v chr="$chr" '$1 == chr {print $1, $4}' OFS='\t' "${subdir}/${sample}_${experiment}_75nt.tsv" | awk 'BEGIN {OFS="\t"} {print $0, NR}' > "${subdir}/${sample}_${experiment}_75nt_${chr}.tsv"
                        
              # Extract MATs
              if [[ $chr == "CHRIII" ]]; then
                awk -F'\t' '$3 >= 199953 && $3 <= 201553' "${subdir}/${sample}_${experiment}_75nt_CHRIII.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRIII_MATa.tsv"
              elif [[ $chr == "CHRV" ]]; then
                awk -F'\t' '$3 >= 289025 && $3 <= 290625' "${subdir}/${sample}_${experiment}_75nt_CHRV.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRV_MATa.tsv"
              fi
            done

            
                    
            # Clean intermediate files
            rm "${subdir}/${sample}_${experiment}_75nt.fastq" "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.bai" "${subdir}/${sample}_${experiment}_75nt.sam"
            rm "${subdir}/${sample}_${experiment}_18nt.fastq" "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.bai" "${subdir}/${sample}_${experiment}_18nt.sam"

          else
          echo "Warning: Decompressed files missing for sample $sample in $subdir!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $subdir!" >> "$log_file"
        echo "" >> "$log_file"
        fi
      done
    done
done




for strain in "$MYWD"*/; do
  echo "Processing directory: $strain to calculate average coverage" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    R_SCRIPT="SR_process_cov_III_V.R"
    strain="${strain}"
    root_dir="${strain}"
    echo "Processing strain: $strain" >> "$log_file"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
          continue
        fi  
done




### === DATA ORGANIZATION ===

#Crate folder for the Alignment output files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Alignment_data"
    mv "${subdir}"/*.bedgraph "${subdir}/Alignment_data/"
done

# Create a folder for the Coverage TSV files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Coverage_data"
    mv "${subdir}"/*_Coverage.tsv "${subdir}/Coverage_data/"
done

for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/MATs_quant_data"
    for chr in CHRIII CHRV; do
        mv "${subdir}"/*_"${chr}"_18nt_nonRPGC_ordered.tsv "${subdir}/MATs_quant_data/"
    done
done

# Create a folder for the graphs
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/Graphs_Coverage"
  mv "${subdir}/plot_"*".svg" "${subdir}/Graphs_Coverage/"
done

# Create a folder for FASTQP files
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/FASTQP"
  mv "${subdir}"/*.fastq.html "${subdir}/FASTQP/"
  mv "${subdir}"/*.fastq.json "${subdir}/FASTQP/"
done

# Remove index files
find "$MYREF" -name "*.ebwt" -exec rm {} +
find "$MYREF" -name "*.fai" -exec rm {} +
find "$MYREF" -name "*.txt" -exec rm {} +

Delete all TSV files in subdir, excluding those in Alignment_data
for subdir in "${MYWD}"*; do
    find "${subdir}" -maxdepth 1 -type f -name "*.tsv" ! -name "*_75nt.tsv" -exec rm {} \;
done
