#!/bin/bash

AUTHORS="Lydia Iglesias, Narciso M. Quijada, Andrés Clemente-Blanco"
LASTMODIF="2026-03-07"
VERSION="0.3.2"
MODIFICATIONS="experiment name dynamically set, MUT"


DiGRAPH=$0
while [ -h "$DiGRAPH" ]; do # resolve $DiGRAPH until the file is no longer a symlink
  DiGRAPHDIR="$( cd -P "$( dirname "$0" )" && pwd )"
  DiGRAPH="$(readlink "$DiGRAPH")"
  [[ $DiGRAPH != /* ]] && DiGRAPH="$DiGRAPHDIR/$DiGRAPH" # if $DiGRAPH is a symlink, resolve it relative to the path where the symlink file was located
done
DiGRAPHDIR="$( cd -P "$( dirname "$DiGRAPH" )" && pwd )"

# WORKING VARIABLES
CATEGORY_PATH=
MYBLAST=
MYREF=
MYREPORT=
MYWD=
MYRSCRIPTS=
STRAIN_REF="no"
NUMBER_EXP=3
N_CPU=$(nproc)
#N_CPU=$(sysctl -n hw.ncpu) #macOS

current_time=
log_file=
stats=

#MYREF=/home/ibfg/GWSL/RG # Replace with the path to your MYREF directory: path/to/RG
#MYWD=/home/ibfg/GWSL/WD/ # Replace with the path to your MYWD directory: path/to/WD
#CATEGORY_PATH=/home/ibfg/GWSL/Categories # Replace with the path to your CATEGORY_PATH directory: path/to/Categories
#MYBLAST=/home/ibfg/GWSL/BLAST/features_extraction # Replace with the path to your MYBLAST directory: path/to/BLAST/features_extraction
#MYREPORT=/home/ibfg/GWSL/Report_files # Replace with the path to your MYREPORT directory: path/to/Report_files

# Message colors
COL_RESET=$(tput sgr 0)
COL_blue=$(tput setaf 4)
COL_cyan=$(tput setaf 6)
COL_green=$(tput setaf 2)
COL_magenta=$(tput setaf 5)
COL_purple=$(tput setaf 5)
COL_red=$(tput setaf 1)
COL_white=$(tput setaf 7)
COL_yellow=$(tput setaf 3)

usage () {

cat << EOF

=============================================================

██████╗               ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗
██╔══██╗  ██╗        ██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║
██║  ██║  ╚═╝  ███╗  ██║  ███╗██████╔╝███████║██████╔╝███████║  
██║  ██║  ██╗  ╚══╝  ██║   ██║██╔╚██╗ ██╔══██║██╔═══╝ ██╔══██║  
██████╔╝  ██║        ╚██████╔╝██║ ╚██╗██║  ██║██║     ██║  ██║
╚═════╝   ╚═╝         ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝

      DSB-induced Genome-wide Repair Analysis 
     and Profiling of Homologous recombination
                   ${VERSION}
 ${AUTHORS}
=============================================================

Description:
This tool performs genome-wide analysis of DNA repair following an HO-induced break. 
Di-GRAPH integrates:
  - MAT repair profiling
  - Genome instability evaluation based on coverage 
  - Recombination analysis based on inter-chromosomal discordant reads
Input files are gzipped paired-end fastq files.

OBLIGATORY OPTIONS:
    -b/--blast          Path to BLAST genomic database for cross-validation directory (provided in GitHub)
    -c/--categories     Path to genomic categories and features annotation directory (provided in GitHub)
    -g/--genome         Path to reference genome directory (provided in GitHub)
    -i/--input          Path to input directory (working directory generated by the user)
    -r/--report         Path to report directory (provided in GitHub)
    -R/--Rscripts       Path to R scripts directory (provided in GitHub)


OTHER OPTIONS:
    -h/--help           Shows this help
    -s/--strain_ref     Name of the strain to be used as a reference (example: 1_Wt)
    -n/--number_exp     Number of experiments (default=3)
    -t/--threads        Number of threads to use (default=${N_CPU})
    -v/--version        Show version

EOF
}

if [ $# == 0 ]; then
	usage
	exit 1
fi

# VARIABLE OPTIONS

POSITIONAL=()
while [[ $# -gt 0 ]]
do
ARGS="$1"

case $ARGS in
    -b|--blast)
    if [ "$2" ]; then
        MYBLAST=$2
        shift 2
        if [ ! -d "${MYBLAST}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYBLAST})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-b/--blast" requires an argument\n'
        exit 1
    fi
    ;;
    -c|--categories)
    if [ "$2" ]; then
        CATEGORY_PATH=$2
        shift 2
        if [ ! -d "${CATEGORY_PATH}" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${CATEGORY_PATH})" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-c/--categories" requires an argument\n'
        exit 1
    fi
    ;;
    -i|--input)
    if [ "$2" ]; then
        MYWD=$2
        shift 2
        if [ ! -d "${MYWD}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYWD})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-i/--input" requires an argument\n'
        exit 1
    fi
    ;;
    -g|--genome)
    if [ "$2" ]; then
        MYREF=$2
        shift 2
        if [ ! -d "${MYREF}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREF})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-g/--genome" requires an argument\n'
        exit 1
    fi
    ;;
    -r|--report)
    if [ "$2" ]; then
        MYREPORT=$2
        shift 2
        if [ ! -d "${MYREPORT}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREPORT})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -R|--Rscripts)
    if [ "$2" ]; then
        MYRSCRIPTS=$2
        shift 2
        if [ ! -d "${MYRSCRIPTS}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYRSCRIPTS} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYRSCRIPTS})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYRSCRIPTS} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-R/--Rscripts" requires an argument\n'
        exit 1
    fi
    ;;
    -s|--strain_ref)
    if [ "$2" ]; then
        STRAIN_REF=$2
        #echo STRAIN_REF=$STRAIN_REF
        shift 2
        if [[ ! -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_red}ERROR: ${STRAIN_REF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [[ -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_green}REFERENCE STRAIN: ${STRAIN_REF} will be used as reference strain!${COL_RESET} \n"
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -n|--number_exp)
    if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NUMBER_EXP=$2
            shift 2
        else
            echo -e '\nERROR: "-n/--number_exp" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-n/--number_exp" requires a numeric argument\n'
        exit 1
    fi
    ;;
    -t|--threads)
	if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NCPUS=$2
            shift 2
        else
            echo -e '\nERROR: "-t/--threads" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-t/--threads" requires a numeric argument\n'
        exit 1
    fi
	;;
    -v|--version)
        echo "${COL_yellow}Di-GRAPH version ${VERSION}${COL_RESET}"
        exit 1
    ;;
    -h|--help)
	    usage
	    exit 1
	;;
    -?*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
	    exit 1
	;;
	*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
        exit 1
    ;;
esac
done
set -- "${POSITIONAL[@]}" #restore positional parameters


REQUIRED_VARS=(MYBLAST CATEGORY_PATH MYWD MYREF MYREPORT MYRSCRIPTS)
REQUIRED_OPTS=(
  "-b/--blast"
  "-c/--categories"
  "-i/--input"
  "-g/--genome"
  "-r/--report"
  "-R/--Rscripts"
)

missing=0

for i in "${!REQUIRED_VARS[@]}"; do
    var="${REQUIRED_VARS[$i]}"
    opt="${REQUIRED_OPTS[$i]}"

    if [ -z "${!var}" ]; then
        echo -e "${COL_red}ERROR:${COL_RESET} Required option $opt is missing"
        missing=1
    fi
done

if [ "$missing" -eq 1 ]; then
    usage
    exit 1
fi

if [[ "$STRAIN_REF" == "no" ]]; then
    echo -e "\n${COL_blue}REFERENCE STRAIN: no reference strain will be used${COL_RESET} \n"
fi

if [[ "$NUMBER_EXP" != 3 ]]; then
    echo -e "\n${COL_blue}NUMBER OF EXPERIMENTS: $NUMBER_EXP experiments will be analyzed${COL_RESET} \n"
fi

read -rp "Please, enter experiment names (comma-separated, e.g. E1,E3,E4): " NAME_EXP

IFS=',' read -ra EXP_LIST <<< "$NAME_EXP"


if [ "${#EXP_LIST[@]}" -ne "$NUMBER_EXP" ]; then
    echo "ERROR: You specified $NUMBER_EXP experiments but provided ${#EXP_LIST[@]} names."
    exit 1
fi

#echo "Working"
#################################

######## Starting the analysis ########
# Create a log and stat file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
log_file="${MYWD}/log_file.txt"
stats="${MYWD}/stats.txt"

# Start timer for the entire script processing
start_time_total_script=$SECONDS

###########################################
########### MUTAGENIC RATE AT HO ########## #Updated on 30/09/2025 #R scripts updated on 07/10/2026
###########################################

current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Mutagenic Rate at HO Analysis - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line 

#Add a line to separate bowtie and bwa alignments in the stat file
echo "=========  BWA Alignment ==========" >> "$stats"
echo "=========  Mutagenic rate at HO - BWA Alignment ==========" >> "$log_file"

# Set locale
export LC_ALL=C
export LANG=C

# Start timer for the entire script processing
start_time_total_mut=$SECONDS

# Index RG
bwa index "${MYREF}/RG_PMV_v9_CHRIII.fasta"

# Loop through each directory inside MYWD for alignments
for subdir in "$MYWD"*/; do
  echo "Processing directory: $subdir"
    for sample in T0 TLG TLR; do
      for exp in "${EXP_LIST[@]}"; do
        file1_gz="${subdir}/${sample}_${exp}_R1.fastq.gz"
        file2_gz="${subdir}/${sample}_${exp}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz"

          # Decompress the current pair
          gunzip -k "$file1_gz" "$file2_gz"
          file1_path="${subdir}/${sample}_${exp}_R1.fastq"
          file2_path="${subdir}/${sample}_${exp}_R2.fastq"

          # Concatenate the two fastq files
          cat "$file1_path" "$file2_path" > "${subdir}/${sample}_${exp}.fastq"
          
          #Filtering and alinging reads
          if [[ -f "${subdir}/${sample}_${exp}.fastq" ]]; then
          
            # Detecting number of available CPUs
            N_CPU=$(nproc)
            
            # Filter reads Q30
            fastp \
            -i "${subdir}/${sample}_${exp}.fastq" \
            -o "${subdir}/${sample}_${exp}_Q30.fastq" \
            -q 30 -u 0 -e 30 \
            --thread "$N_CPU" \
            --html "${subdir}/${sample}_${exp}_Q30.fastq.html" \
            --json "${subdir}/${sample}_${exp}_Q30.fastq.json"
                
            # BWA mapping
            bwa mem -t "$N_CPU" "${MYREF}/RG_PMV_v9_CHRIII.fasta" "${subdir}/${sample}_${exp}_Q30.fastq" > "${subdir}/${sample}_${exp}_Q30.sam"

            # Filtering CHRIII reads
            sed -n -e '1,2p' "${subdir}/${sample}_${exp}_Q30.sam" > "${subdir}/${sample}_${exp}_cabecera.sam"
            awk '$3 == "CHRIII"' "${subdir}/${sample}_${exp}_Q30.sam" > "${subdir}/${sample}_${exp}_Q30_CHRIII.sam"
            cat "${subdir}/${sample}_${exp}_cabecera.sam" "${subdir}/${sample}_${exp}_Q30_CHRIII.sam" > "${subdir}/${sample}_${exp}_Q30_CHRIII_header.sam"
          
            # Convert SAM to sorted BAM
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${exp}_processed.bam" "${subdir}/${sample}_${exp}_Q30_CHRIII_header.sam"
            samtools index "${subdir}/${sample}_${exp}_processed.bam" "${subdir}/${sample}_${exp}_processed.bai"

            # Extact reads mapping to the HO site
            samtools view "${subdir}/${sample}_${exp}_processed.bam" "CHRIII:200753-200753" -h -O SAM > "${subdir}/${sample}_${exp}_HOs.sam"
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${exp}_HOs.bam" "${subdir}/${sample}_${exp}_HOs.sam"
            samtools index "${subdir}/${sample}_${exp}_HOs.bam" "${subdir}/${sample}_${exp}_HOs.bai"
            echo "" >> "$stats"
            echo "### $(basename "$subdir")/${sample}/${exp} 150nt ###" >> "$stats"
            echo "BWA Alignment: Reads mappint the HO site" >> "$stats"
            samtools flagstat "${subdir}/${sample}_${exp}_HOs.bam" | head -n 1 >> "$stats"

            # Remove intermediate files
            rm "${subdir}"/*.fastq "${subdir}"/*.sam
            
          else
          echo "Warning: Decompressed files missing for sample $sample in $subdir!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $subdir!" >> "$log_file"
        echo "" >> "$log_file"
        fi
      done
    done
done

# Remove intermediate files
find "$MYWD" -type f \( -name "*.sam" -o -name "*.fastq" \) -exec rm {} + # intermediate alignmet files

### DATA ANALYSIS ###

# Start timer for data analysis and plotting

### Invoque python script to extract reads with A or G at postion 200689 ###

for subdir in "$MYWD"*/; do
  for sample in T0 TLG TLR; do
    for exp in "${EXP_LIST[@]}"; do
      bam_file="${subdir}/${sample}_${exp}_HOs.bam"
      output_bam_G="${subdir}/${sample}_${exp}_200689_G.bam"
      output_bam_A="${subdir}/${sample}_${exp}_200689_A.bam"
      if [[ -f "$bam_file" ]]; then
        echo "Processing BAM file: $bam_file"
      else
        echo "Warning: BAM file $bam_file does not exist!"
      fi
  
python3 <<EOF
import pysam
import sys

def extract_reads(bam_file, nucleotide, output_bam, ref_name, position):
    try:
        # Open input BAM
        bam = pysam.AlignmentFile(bam_file, "rb")
        
        # Open output BAM (using input as template)
        out_bam = pysam.AlignmentFile(output_bam, "wb", template=bam)
        
        # Fetch reads overlapping the position (1-based in pysam)
        for read in bam.fetch(ref_name, position-1, position):
            # Skip if no sequence (e.g., unmapped reads)
            if not read.query_sequence:
                continue
            
            # Get aligned pairs (query-to-reference positions)
            aligned_pairs = read.get_aligned_pairs(matches_only=True)
            
            # Check each aligned base
            for query_pos, ref_pos in aligned_pairs:
                # If this is the target position (0-based)
                if ref_pos == position - 1:
                    # Check if the base matches the desired nucleotide
                    if read.query_sequence[query_pos] == nucleotide:
                        out_bam.write(read)
                        break  # Stop checking this read once matched
        
        # Close files
        bam.close()
        out_bam.close()
    
    except Exception as e:
        print(f"ERROR: Failed to process {bam_file} for {nucleotide}: {e}", file=sys.stderr)
        sys.exit(1)

# ===== Parameters =====
bam_file = "${bam_file}"          # Input BAM file
ref_name = "CHRIII"               # Reference chromosome
position = 200689                 # 1-based genomic position
nucleotideA = "A"                 # Nucleotide to extract (A)
output_bam_A = "${output_bam_A}"  # Output BAM for A reads
nucleotideG = "G"                 # Nucleotide to extract (G)
output_bam_G = "${output_bam_G}"  # Output BAM for G reads

# ===== Run Extraction =====
extract_reads(bam_file, nucleotideA, output_bam_A, ref_name, position)
extract_reads(bam_file, nucleotideG, output_bam_G, ref_name, position)
EOF

    #Generate bai index for the new bam files
    samtools index "${output_bam_A}" "${output_bam_A}.bai"
    samtools index "${output_bam_G}" "${output_bam_G}.bai"

    # Add stats to the log file
    echo "Read count for A at 200689: $(samtools view -c "${output_bam_A}")" 
    #samtools view -c "${output_bam_A}" > "${subdir}/${sample}_${exp}_200689A_row_count.tsv"
    echo "Read count for G at 200689: $(samtools view -c "${output_bam_G}")" 
    samtools view -c "${output_bam_G}" > "${subdir}/${sample}_${exp}_200689G_row_count.tsv"
    done
  done
done

### Invoque python script to extract reads with T or C at postion 200753 from reads with A at position 200689 ###

for subdir in "$MYWD"*/; do
  for sample in T0 TLG TLR; do
    for exp in "${EXP_LIST[@]}"; do
      bam_file="${subdir}/${sample}_${exp}_200689_A.bam"
      output_bam_T="${subdir}/${sample}_${exp}_200689_A_200753_T.bam"
      output_bam_C="${subdir}/${sample}_${exp}_200689_A_200753_C.bam"
      if [[ -f "$bam_file" ]]; then
        echo "Processing BAM file: $bam_file"
      else
        echo "Warning: BAM file $bam_file does not exist!"
      fi
  
python3 <<EOF
import pysam
import sys

def extract_reads(bam_file, nucleotide, output_bam, ref_name, position):
    try:
        # Open input BAM
        bam = pysam.AlignmentFile(bam_file, "rb")
        
        # Open output BAM (using input as template)
        out_bam = pysam.AlignmentFile(output_bam, "wb", template=bam)
        
        # Fetch reads overlapping the position (1-based in pysam)
        for read in bam.fetch(ref_name, position-1, position):
            # Skip if no sequence (e.g., unmapped reads)
            if not read.query_sequence:
                continue
            
            # Get aligned pairs (query-to-reference positions)
            aligned_pairs = read.get_aligned_pairs(matches_only=True)
            
            # Check each aligned base
            for query_pos, ref_pos in aligned_pairs:
                # If this is the target position (0-based)
                if ref_pos == position - 1:
                    # Check if the base matches the desired nucleotide
                    if read.query_sequence[query_pos] == nucleotide:
                        out_bam.write(read)
                        break  # Stop checking this read once matched
        
        # Close files
        bam.close()
        out_bam.close()
    
    except Exception as e:
        print(f"ERROR: Failed to process {bam_file} for {nucleotide}: {e}", file=sys.stderr)
        sys.exit(1)

# ===== Parameters =====
bam_file = "${bam_file}"          # Input BAM file
ref_name = "CHRIII"               # Reference chromosome
position = 200753                 # 1-based genomic position
nucleotideT = "T"                 # Nucleotide to extract (T)
output_bam_T = "${output_bam_T}"  # Output BAM for T reads
nucleotideC = "C"                 # Nucleotide to extract (T)
output_bam_C = "${output_bam_C}"  # Output BAM for C reads

# ===== Run Extraction =====
extract_reads(bam_file, nucleotideT, output_bam_T, ref_name, position)
extract_reads(bam_file, nucleotideC, output_bam_C, ref_name, position)
EOF

    #Generate bai index for the new bam files
    samtools index "${output_bam_T}" "${output_bam_T}.bai"
    samtools index "${output_bam_C}" "${output_bam_C}.bai"
    # Add stats to the log file
    echo "Read count for T at 200753 and A at 200689: $(samtools view -c "${output_bam_T}")" 
    samtools view -c "${output_bam_T}" > "${subdir}/${sample}_${exp}_200689AT_row_count.tsv"
    echo "Read count for C at 200753 and A at 200689: $(samtools view -c "${output_bam_C}")"
    samtools view -c "${output_bam_C}" > "${subdir}/${sample}_${exp}_200689AC_row_count.tsv"



    # Merge the two bam files
    samtools merge -f "${subdir}/${sample}_${exp}_200689_A_CT.bam" "${output_bam_C}" "${output_bam_T}"
    samtools view -c "${subdir}/${sample}_${exp}_200689_A_CT.bam" > "${subdir}/${sample}_${exp}_200689ACT_row_count.tsv"
    samtools index "${subdir}/${sample}_${exp}_200689_A_CT.bam" "${subdir}/${sample}_${exp}_200689_A_CT.bai"
    samtools merge -f "${subdir}/${sample}_${exp}_200689_A_CT_G.bam" "${subdir}/${sample}_${exp}_200689_A_CT.bam" "${subdir}/${sample}_${exp}_200689_G.bam"
    samtools view -c "${subdir}/${sample}_${exp}_200689_A_CT_G.bam" > "${subdir}/${sample}_${exp}_200689ACTG_row_count.tsv"
    samtools index "${subdir}/${sample}_${exp}_200689_A_CT_G.bam" "${subdir}/${sample}_${exp}_200689_A_CT_G.bai"
    
    ### Assesing IGVtools for Del and Ins ###
    
    # Extract base scores usign bcftools
    ref_fasta="${MYREF}/RG_PMV_v9_CHRIII.fasta"

    # Define the path to igvtools
    bam_file_igv_A_CT="${subdir}/${sample}_${exp}_200689_A_CT.bam"
    bam_file_igv_A_CT_G="${subdir}/${sample}_${exp}_200689_A_CT_G.bam"
    bam_file_igv_A_200753_T="${subdir}/${sample}_${exp}_200689_A_200753_T.bam"
    bam_file_igv_A_200753_C="${subdir}/${sample}_${exp}_200689_A_200753_C.bam"
    bam_file_igv_G="${subdir}/${sample}_${exp}_200689_G.bam"
    ref_fasta="${MYREF}/RG_PMV_v9_CHRIII.fasta"

    # Create a loop to assess 200689  ACTG, ATG, A_T, A_C or G polymorphisms
      ### Assesisng IGVtools - Del and Ins ###
      for poly in A_CT A_CT_G A_200753_T A_200753_C G ; do
        wig_output="${subdir}/${sample}_${exp}_200689_${poly}.wig"
        var_name="bam_file_igv_${poly}"
        bam_file="${!var_name}" # indirect expansion
      
        # Run igvtools to generate the WIG file
        igvtools count -w 1 --bases --query CHRIII:200743-200762 "$bam_file" "$wig_output" "$ref_fasta"


        ### Assesing nucleotide variants by BCFtools ###

        tsv_output_BCF="${subdir}/${sample}_${exp}_${poly}_BCF.tsv"
        bam_file="${subdir}/${sample}_${exp}_200689_${poly}.bam"      
        vcf_file="${subdir}/${sample}_${exp}_${poly}_variants.vcf.gz"

        # Variant calling
        bcftools mpileup -Ou -f "$ref_fasta" -r CHRIII:200742-200762 "$bam_file" | \
        bcftools call -mA --ploidy 1 -Oz -o "$vcf_file"
        bcftools index "$vcf_file"

        # Fill in missing INFO tags like AF, AN, AC
        vcf_with_af="${vcf_file%.vcf.gz}_with_AF.vcf.gz"
        bcftools +fill-tags "$vcf_file" -Oz -o "$vcf_with_af" -- -t AF,AN,AC
        bcftools index "$vcf_with_af"

        # Extract the region and required fields
        filtered_vcf="${vcf_with_af%.vcf.gz}.filtered.vcf"
        bcftools view -r CHRIII:200743-200762 "$vcf_with_af" > "$filtered_vcf"
        bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/DP\t%INFO/DP4\n' "$vcf_file" | \
        awk 'BEGIN { OFS="\t" }
        {
            split($6, dp4, ",");
            ref_count = dp4[1] + dp4[2];
            alt_count = dp4[3] + dp4[4];
            total = ref_count + alt_count;
            af = (total == 0) ? 0 : int((alt_count / total) * 100);
            print $1, $2, $3, $4, $5, af
        }' > "$tsv_output_BCF"

        find "$MYWD" -type f \( -name "*.vcf" -o -name "*.vcf.gz" -o -name "*.csi" \) -exec rm {} + # BCF intermediate files
         done
    done
  done
done

### Calculate repair pathway frequency
R_SCRIPT="MUT_calc_rep_path_freq.R"

for strain in "${MYWD}"*/; do

    echo "Processing directory: ${strain}" >> "$log_file"

    root_dir="${strain}"
    wd_dir="${MYWD}"

    echo "$(basename "$strain")" >> "$log_file"
    echo "" >> "$log_file"
    echo "Plotting repair_pathway for ${strain}" >> "$log_file"

    if ! Rscript "${MYRSCRIPTS}/${R_SCRIPT}" "$root_dir" "$strain" "$wd_dir" 2>> "$log_file"; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
        echo "Skipping ${strain} and continuing..." >> "$log_file"
        continue
    fi

done


### Plot repair pathway comparison
R_SCRIPT="MUT_plot_rep_path_comparison.R"

echo "Processing directory: ${MYWD}" >> "$log_file"
root_dir="${MYWD}"
echo "Plotting repair_pathway comparison" >> "$log_file"
start_time=$SECONDS
if ! Rscript "${MYRSCRIPTS}/${R_SCRIPT}" "$root_dir" 2>> "$log_file"; then
  echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
  echo "Skipping ${root_dir} and continuing..." >> "$log_file"
fi
      

# Calculate total elapsed time
elapsed_time_total_mut=$((( SECONDS - start_time_total_mut )/60))
echo "Mutagenic Rate at HO Analysis completed in ${elapsed_time_total_mut} minutes" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line



# === ORGANIZING DATA ===

# Remove intermediate files
find "$MYWD" -type f \( -name "*_BFC.tsv" \) -exec rm {} + # BCF.tsv intermediate files

# Move data into subfolders
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/HO_mut_rate/FASTQP" "${subdir}/HO_mut_rate/SVG" "${subdir}/HO_mut_rate/TSV"
  mv "${subdir}"/*.fastq.html "${subdir}/HO_mut_rate/FASTQP/" 2> /dev/null
  mv "${subdir}"/*.fastq.json "${subdir}/HO_mut_rate/FASTQP/" 2> /dev/null
  mv "${subdir}"/*.svg "${subdir}/HO_mut_rate/SVG/" 2> /dev/null
  mv "${subdir}"/*.tsv "${subdir}/HO_mut_rate/TSV/" 2> /dev/null
done

# Remove unecesary files
find "$MYREF" \( -name "*.amb" -o -name "*.ann" -o -name "*.bwt" -o -name "*.pac" -o -name "*.sa" -o -name "*.fai" \) -exec rm {} + # index files
find "$MYWD" -type f \( -name "*.bai" -o -name "*.bam" \) -exec rm {} + # intermediate alignmet files
find "$MYWD" -type f \( -name "*.vcf" -o -name "*.vcf.gz" -o -name "*.csi" \) -exec rm {} + # BCF intermediate files
find "$MYWD" -type f \( -name "*.wig" \) -exec rm {} + # WIG intermediate files



# Calculate total elapsed time
elapsed_time_total_mut=$((( SECONDS - start_time_total_mut )/60))
echo "HO Mutagenic Rate Analysis completed in ${elapsed_time_total_mut} minutes" >> "$log_file"
echo "" >> "$log_file"