#!/bin/bash

AUTHORS="Lydia Iglesias, Narciso M. Quijada, Andrés Clemente-Blanco"
LASTMODIF="2026-06-28"
VERSION="0.4"
MODIFICATIONS="experiment name dynamically set, ONLY MATa-MATa' analysis, only TSG"


DiGRAPH=$0
while [ -h "$DiGRAPH" ]; do # resolve $DiGRAPH until the file is no longer a symlink
  DiGRAPHDIR="$( cd -P "$( dirname "$0" )" && pwd )"
  DiGRAPH="$(readlink "$DiGRAPH")"
  [[ $DiGRAPH != /* ]] && DiGRAPH="$DiGRAPHDIR/$DiGRAPH" # if $DiGRAPH is a symlink, resolve it relative to the path where the symlink file was located
done
DiGRAPHDIR="$( cd -P "$( dirname "$DiGRAPH" )" && pwd )"

# WORKING VARIABLES
CATEGORY_PATH=
MYBLAST=
MYREF=
MYREPORT=
MYWD=
MYSCRIPTS=
STRAIN_REF="no"
NUMBER_EXP=3
N_CPU=$(nproc)
#N_CPU=$(sysctl -n hw.ncpu) #macOS

current_time=
log_file=
stats=

#MYREF=/home/ibfg/GWSL/RG # Replace with the path to your MYREF directory: path/to/RG
#MYWD=/home/ibfg/GWSL/WD/ # Replace with the path to your MYWD directory: path/to/WD
#CATEGORY_PATH=/home/ibfg/GWSL/Categories # Replace with the path to your CATEGORY_PATH directory: path/to/Categories
#MYBLAST=/home/ibfg/GWSL/BLAST/features_extraction # Replace with the path to your MYBLAST directory: path/to/BLAST
#MYREPORT=/home/ibfg/GWSL/Report_files # Replace with the path to your MYREPORT directory: path/to/Report_files

# Message colors
COL_RESET=$(tput sgr 0)
COL_blue=$(tput setaf 4)
COL_cyan=$(tput setaf 6)
COL_green=$(tput setaf 2)
COL_magenta=$(tput setaf 5)
COL_purple=$(tput setaf 5)
COL_red=$(tput setaf 1)
COL_white=$(tput setaf 7)
COL_yellow=$(tput setaf 3)

usage () {

cat << EOF

=============================================================

██████╗               ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗
██╔══██╗  ██╗        ██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║
██║  ██║  ╚═╝  ███╗  ██║  ███╗██████╔╝███████║██████╔╝███████║  
██║  ██║  ██╗  ╚══╝  ██║   ██║██╔╚██╗ ██╔══██║██╔═══╝ ██╔══██║  
██████╔╝  ██║        ╚██████╔╝██║ ╚██╗██║  ██║██║     ██║  ██║
╚═════╝   ╚═╝         ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝

      DSB-induced Genome-wide Repair Analysis 
     and Profiling of Homologous recombination
                   ${VERSION}
 ${AUTHORS}
=============================================================

Description:
This tool performs genome-wide analysis of DNA repair following an HO-induced break. 
Di-GRAPH integrates:
  - MAT repair profiling
  - Genome instability evaluation based on coverage 
  - Recombination analysis based on inter-chromosomal discordant reads
Input files are gzipped paired-end fastq files.

OBLIGATORY OPTIONS:
    -b/--blast          Path to BLAST genomic database for cross-validation directory (provided in GitHub)
    -c/--categories     Path to genomic categories and features annotation directory (provided in GitHub)
    -g/--genome         Path to reference genome directory (provided in GitHub)
    -i/--input          Path to input directory (working directory generated by the user)
    -r/--report         Path to report directory (provided in GitHub)
    -S/--scripts        Path to scripts directory (provided in GitHub)


OTHER OPTIONS:
    -h/--help           Shows this help
    -s/--strain_ref     Name of the strain to be used as a reference (example: 1_Wt)
    -n/--number_exp     Number of experiments (default=3)
    -t/--threads        Number of threads to use (default=${N_CPU})
    -v/--version        Show version

EOF
}

if [ $# == 0 ]; then
	usage
	exit 1
fi

# VARIABLE OPTIONS

POSITIONAL=()
while [[ $# -gt 0 ]]
do
ARGS="$1"

case $ARGS in
    -b|--blast)
    if [ "$2" ]; then
        MYBLAST=$2
        shift 2
        if [ ! -d "${MYBLAST}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYBLAST})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-b/--blast" requires an argument\n'
        exit 1
    fi
    ;;
    -c|--categories)
    if [ "$2" ]; then
        CATEGORY_PATH=$2
        shift 2
        if [ ! -d "${CATEGORY_PATH}" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${CATEGORY_PATH})" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-c/--categories" requires an argument\n'
        exit 1
    fi
    ;;
    -i|--input)
    if [ "$2" ]; then
        MYWD=$2
        shift 2
        if [ ! -d "${MYWD}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYWD})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-i/--input" requires an argument\n'
        exit 1
    fi
    ;;
    -g|--genome)
    if [ "$2" ]; then
        MYREF=$2
        shift 2
        if [ ! -d "${MYREF}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREF})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-g/--genome" requires an argument\n'
        exit 1
    fi
    ;;
    -r|--report)
    if [ "$2" ]; then
        MYREPORT=$2
        shift 2
        if [ ! -d "${MYREPORT}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREPORT})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -S|--scripts)
    if [ "$2" ]; then
        MYSCRIPTS=$2
        shift 2
        if [ ! -d "${MYSCRIPTS}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYSCRIPTS})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-R/--Rscripts" requires an argument\n'
        exit 1
    fi
    ;;
    -s|--strain_ref)
    if [ "$2" ]; then
        STRAIN_REF=$2
        #echo STRAIN_REF=$STRAIN_REF
        shift 2
        if [[ ! -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_red}ERROR: ${STRAIN_REF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [[ -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_cyan}REFERENCE STRAIN: ${STRAIN_REF} will be used as reference strain!${COL_RESET} \n"
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -n|--number_exp)
    if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NUMBER_EXP=$2
            shift 2
        else
            echo -e '\nERROR: "-n/--number_exp" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-n/--number_exp" requires a numeric argument\n'
        exit 1
    fi
    ;;
    -t|--threads)
	if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NCPUS=$2
            shift 2
        else
            echo -e '\nERROR: "-t/--threads" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-t/--threads" requires a numeric argument\n'
        exit 1
    fi
	;;
    -v|--version)
        echo "${COL_yellow}Di-GRAPH version ${VERSION}${COL_RESET}"
        exit 1
    ;;
    -h|--help)
	    usage
	    exit 1
	;;
    -?*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
	    exit 1
	;;
	*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
        exit 1
    ;;
esac
done
set -- "${POSITIONAL[@]}" #restore positional parameters


REQUIRED_VARS=(MYBLAST CATEGORY_PATH MYWD MYREF MYREPORT MYSCRIPTS)
REQUIRED_OPTS=(
  "-b/--blast"
  "-c/--categories"
  "-i/--input"
  "-g/--genome"
  "-r/--report"
  "-S/--scripts"
)

missing=0

for i in "${!REQUIRED_VARS[@]}"; do
    var="${REQUIRED_VARS[$i]}"
    opt="${REQUIRED_OPTS[$i]}"

    if [ -z "${!var}" ]; then
        echo -e "${COL_red}ERROR:${COL_RESET} Required option $opt is missing"
        missing=1
    fi
done

if [ "$missing" -eq 1 ]; then
    usage
    exit 1
fi

if [[ "$STRAIN_REF" == "no" ]]; then
    echo -e "\n${COL_blue}REFERENCE STRAIN: no reference strain will be used${COL_RESET} \n"
fi

if [[ "$NUMBER_EXP" != 3 ]]; then
    echo -e "\n${COL_blue}NUMBER OF EXPERIMENTS: $NUMBER_EXP experiments will be analyzed${COL_RESET} \n"
fi

read -rp "Please, enter experiment names (comma-separated, e.g. E1,E3,E4): " NAME_EXP

IFS=',' read -ra EXP_LIST <<< "$NAME_EXP"


if [ "${#EXP_LIST[@]}" -ne "$NUMBER_EXP" ]; then
    echo "ERROR: You specified $NUMBER_EXP experiments but provided ${#EXP_LIST[@]} names."
    exit 1
fi
#echo "Working"
#################################

######## Starting the analysis ########
# Create a log and stat file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
log_file="${MYWD}/log_file.txt"
stats="${MYWD}/stats.txt"

# Start timer for the entire script processing
start_time_total_script=$SECONDS

echo "CONCORDANT ANALYSIS - initiated at: \"$current_time\"" > "$log_file"
echo "" >> "$log_file"  # Adds a blank line

echo "=========  Bowtie Alignment ==========" >> "$stats"


# Index RG
bowtie-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed" #NMQ --> MOVE TO INSTALL!


###########################################
### COVERAGE AND POLYMORPHISMS ANALYSIS ###
###########################################

echo "Coverage and Polymorphisms Analysis - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line

# Start timers for Coverage and Polymorphism Analysis processing

start_time_total_cov=$SECONDS

# Loop through each directory inside MYWD
for subdir in "$MYWD"*/; do
  echo "Processing directory: $subdir" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    for sample in T0 TSG; do
      for experiment in "${EXP_LIST[@]}"; do
        file1_gz="${subdir}/${sample}_${experiment}_R1.fastq.gz"
        file2_gz="${subdir}/${sample}_${experiment}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz" >> "$log_file"
          echo "" >> "$log_file"  # Adds a blank line

          # Decompress the current pair
          gunzip -k "$file1_gz" "$file2_gz"
          file1_path="${subdir}/${sample}_${experiment}_R1.fastq"
          file2_path="${subdir}/${sample}_${experiment}_R2.fastq"
          
          # Concatenate the two fastq files
          cat "$file1_path" "$file2_path" > "${subdir}/${sample}_${experiment}.fastq"
                
          # Remove original fastq files
          rm "$file1_path" "$file2_path"

          if [[ -f "${subdir}/${sample}_${experiment}.fastq" ]]; then
    
            # Trim reads using cutadapt
            cutadapt -j "$N_CPU" --cut -75 -o "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${subdir}/${sample}_${experiment}_2.fastq" "${subdir}/${sample}_${experiment}.fastq"
                    
            # Cut 38nt from the beginning and 38nt from the end
            cutadapt -j "$N_CPU" --cut -38 -o "${subdir}/${sample}_${experiment}_1_1.fastq" "${subdir}/${sample}_${experiment}_1.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${subdir}/${sample}_${experiment}_1_2.fastq" "${subdir}/${sample}_${experiment}_1.fastq"
            cutadapt -j "$N_CPU" --cut -38 -o "${subdir}/${sample}_${experiment}_2_1.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${subdir}/${sample}_${experiment}_2_2.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            
            # Cut 19nt from the beginning and 19nt from the end
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_1_1_1.fastq" "${subdir}/${sample}_${experiment}_1_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_1_1_2.fastq" "${subdir}/${sample}_${experiment}_1_1.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_1_2_1.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_1_2_2.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_2_1_1.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_2_1_2.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_2_2_1.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_2_2_2.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            
            # Remove intermediate files
            rm "${subdir}/${sample}_${experiment}_1_1.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            
            # Catenate processed reads into a single fastq file
            cat "${subdir}/${sample}_${experiment}_18nts"*".fastq" > "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq"
            
                # Filter 18nt reads Q30
                fastp \
                  -i "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq" \
                  -o "${subdir}/${sample}_${experiment}_18nt.fastq" \
                  -q 30 -u 0 -e 30 \
                  --thread "$N_CPU" \
                  --html "${subdir}/${sample}_${experiment}_18nt.fastq.html" \
                  --json "${subdir}/${sample}_${experiment}_18nt.fastq.json" 
                rm "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq" # Remove intermediate 18nt fastq files
            
            # Remove intermediate 18nt fastq files
            rm "${subdir}/${sample}_${experiment}_18nts"*".fastq"

            # Remove intermediate fastq files
            rm "${subdir}/${sample}_${experiment}.fastq"

            # Concatenate processed 75nt reads into a single fastq file
            cat "${subdir}/${sample}_${experiment}_1.fastq" \
                "${subdir}/${sample}_${experiment}_2.fastq" \
              > "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq"
                    
                # Filter 75nt reads Q30
                fastp \
                  -i "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" \
                  -o "${subdir}/${sample}_${experiment}_75nt.fastq" \
                  -q 30 -u 0 -e 30 \
                  --thread "$N_CPU" \
                  --html "${subdir}/${sample}_${experiment}_75nt.fastq.html" \
                  --json "${subdir}/${sample}_${experiment}_75nt.fastq.json"
                rm "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" # Remove intermediate 75nt fastq files
                
            # Remove intermediate 75nt fastq files
            rm "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            
            # Bowtie mapping
            echo "### $(basename "$subdir")/${sample}/${experiment} 75nt ###" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed" "${subdir}/${sample}_${experiment}_75nt.fastq" > "${subdir}/${sample}_${experiment}_75nt.sam" 2>> "$stats"
            echo "" >> "$stats"
                    
            # Aligning using 18nt reads, in -k mode
            echo "### $(basename "$subdir")/${sample}/${experiment} 18nt ###" >> "$stats"
            bowtie -p "$N_CPU" -k 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed" "${subdir}/${sample}_${experiment}_18nt.fastq" > "${subdir}/${sample}_${experiment}_18nt.sam" 2>> "$stats"
            echo "" >> "$stats"

            # Convert SAM to sorted BAM (75nt)
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.sam"
            samtools index "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.bai"
                    
            # Convert SAM to sorted BAM (18nt)
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.sam"
            samtools index "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.bai"
                    
            # Generate BedGraphs coverage files (75nt)
            bamCoverage -b "${subdir}/${sample}_${experiment}_75nt.bam" -o "${subdir}/${sample}_${experiment}_75nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230

            # Sorting Bedgraphs files (75nt)
            samtools faidx "${MYREF}/RG_PMV_v9.fasta" # Create index file
            cut -f1,2 "${MYREF}/RG_PMV_v9.fasta.fai" > "${MYREF}/chrom_order.txt"
            bedtools sort -i "${subdir}/${sample}_${experiment}_75nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_75nt_sorted.bedgraph"
                    
            # Generate BedGraphs coverage files (18nt)
            bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRIII_18nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230 -r CHRIII:199953:201553
            bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRV_18nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230 -r CHRV:289025:290625

            # Sorting Bedgraphs files (18nt)            
            bedtools sort -i "${subdir}/${sample}_${experiment}_CHRIII_18nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_sorted.bedgraph"
            bedtools sort -i "${subdir}/${sample}_${experiment}_CHRV_18nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRV_18nt_sorted.bedgraph"

            # For TSG, TLG and TLR, generate BedGraphs coverage files (18nt) nonRPGC for quantifications
            if [[ "$sample" == "TSG" ]]; then
              bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --effectiveGenomeSize 14272230 -r CHRIII:199953:201553
              bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --effectiveGenomeSize 14272230 -r CHRV:289025:290625

              # Sorting Bedgraphs files (18nt_nonRPGC)
              bedtools sort -i "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_sorted.bedgraph"
              bedtools sort -i "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.bedgraph" -g "${MYREF}/chrom_order.txt"> "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_sorted.bedgraph"
            fi

            # Generate TSV files (75nt)
            bedtools coverage -a "${subdir}/${sample}_${experiment}_75nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_75nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_75nt.tsv"
            
            # Generate TSV files (18nt)
            bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRIII_18nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv"
            bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRV_18nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv"

            # For TSG, TLG and TLR, generate TSV files (18nt) nonRPGC for quantifications
            if [[ "$sample" == "TSG" ]]; then
              bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv"
              bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv"
            fi
                    
            # Reduced decimals in coverage column (4th) (75nt) # Link this file for next blocks!!
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_75nt.tsv" > "${subdir}/${sample}_${experiment}_75nt.tmp" && mv "${subdir}/${sample}_${experiment}_75nt.tmp" "${subdir}/${sample}_${experiment}_75nt.tsv" # Linking file for next blocks!!!

            # Reduced decimals in coverage column (4th) (18nt)
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt.tmp" && mv "${subdir}/${sample}_${experiment}_CHRIII_18nt.tmp" "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv"
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt.tmp" && mv "${subdir}/${sample}_${experiment}_CHRV_18nt.tmp" "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv"
            
            # For TSG, TLG and TLR reduced decimals in coverage column (4th) nonRPGC for quantifications
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tmp" && mv "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tmp" "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv"
              awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tmp" && mv "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tmp" "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv"
            fi

            # Extract CHRIII and CHRV, remove columnes 2, 3, 5, 6, and add coordinates to the last column (75nt)
            for chr in CHRIII CHRV; do
              awk -F'\t' -v chr="$chr" '$1 == chr {print $1, $4}' OFS='\t' "${subdir}/${sample}_${experiment}_75nt.tsv" | awk 'BEGIN {OFS="\t"} {print $0, NR}' > "${subdir}/${sample}_${experiment}_75nt_${chr}.tsv"
                        
              # Extract MATs
              if [[ $chr == "CHRIII" ]]; then
                awk -F'\t' '$3 >= 199953 && $3 <= 201553' "${subdir}/${sample}_${experiment}_75nt_CHRIII.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRIII_MATa.tsv"
              elif [[ $chr == "CHRV" ]]; then
                awk -F'\t' '$3 >= 289025 && $3 <= 290625' "${subdir}/${sample}_${experiment}_75nt_CHRV.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRV_MATa.tsv"
              fi
            done

            # Remove columnes 2, 3, 5, 6, and add coordinates to the last column (18nt)

            awk -F'\t' 'BEGIN {OFS="\t"} {coord=199953+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_ordered.tsv"
            awk -F'\t' 'BEGIN {OFS="\t"} {coord=289025+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_ordered.tsv"

            # For TSG, TLG and TLR, remove columnes 2, 3, 5, 6, and add coordinates to the last column (nonRPGC for quantifications)
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              awk -F'\t' 'BEGIN {OFS="\t"} {coord=199953+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_ordered.tsv"
              awk -F'\t' 'BEGIN {OFS="\t"} {coord=289025+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_ordered.tsv"
            fi
                    
            # Clean intermediate files
            rm "${subdir}/${sample}_${experiment}_75nt.fastq" "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.bai" "${subdir}/${sample}_${experiment}_75nt.sam"
            rm "${subdir}/${sample}_${experiment}_18nt.fastq" "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.bai" "${subdir}/${sample}_${experiment}_18nt.sam"

          else
          echo "Warning: Decompressed files missing for sample $sample in $subdir!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $subdir!" >> "$log_file"
        echo "" >> "$log_file"
        fi
      done
    done
done




for strain in "$MYWD"*/; do
  echo "Processing directory: $strain to calculate average coverage" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    R_SCRIPT="SR_process_cov_III_V.R"
    strain="${strain}"
    root_dir="${strain}"
    echo "Processing strain: $strain" >> "$log_file"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
          continue
        fi  
done




### === DATA ORGANIZATION ===

#Crate folder for the Alignment output files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Alignment_data"
    mv "${subdir}"/*.bedgraph "${subdir}/Alignment_data/"
done

# Create a folder for the Coverage TSV files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Coverage_data"
    mv "${subdir}"/*_Coverage.tsv "${subdir}/Coverage_data/"
done

for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/MATs_quant_data"
    for chr in CHRIII CHRV; do
        mv "${subdir}"/*_"${chr}"_18nt_nonRPGC_ordered.tsv "${subdir}/MATs_quant_data/"
    done
done

# Create a folder for the graphs
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/Graphs_Coverage"
  mv "${subdir}/plot_"*".svg" "${subdir}/Graphs_Coverage/"
done

# Create a folder for FASTQP files
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/FASTQP"
  mv "${subdir}"/*.fastq.html "${subdir}/FASTQP/"
  mv "${subdir}"/*.fastq.json "${subdir}/FASTQP/"
done

# Remove index files
find "$MYREF" -name "*.ebwt" -exec rm {} +
find "$MYREF" -name "*.fai" -exec rm {} +
find "$MYREF" -name "*.txt" -exec rm {} +

# Delete all TSV files in subdir, excluding those in Alignment_data
for subdir in "${MYWD}"*; do
    find "${subdir}" -maxdepth 1 -type f -name "*.tsv" ! -name "*_75nt.tsv" -exec rm {} \;
done



### === MATs quantification for TSG, TLG and TLR ===
# This section calculates the difference in coverage for polymorphism between CHRIII and CHRV

# Coordinates (you can add more coordinates separated by space)
coordinates_CHRIII=(200119 200167 200212 200272 200326 200386 200449 200509 200542 200575 200635 200689 200753 200817 200882 200947 201012 201077 201148 201207 201272 201337 201402)
coordinates_CHRV=(289191 289239 289284 289344 289398 289458 289521 289581 289614 289647 289707 289761 289825 289889 289954 290019 290084 290149 290220 290278 290343 290408 290473)

offset=19 

for subdir in "$MYWD"*/MATs_quant_data/; do
  for sample in TSG; do
    for exp in "${EXP_LIST[@]}"; do
      input_file_CHRIII="${subdir}/${sample}_${exp}_CHRIII_18nt_nonRPGC_ordered.tsv"
      input_file_CHRV="${subdir}/${sample}_${exp}_CHRV_18nt_nonRPGC_ordered.tsv"

      if [[ -f "$input_file_CHRIII" && -f "$input_file_CHRV" ]]; then
        echo "Processing files in $subdir for $sample _ $exp..."

        # Loop through CHRIII coordinates
        for coordinate_CHRIII in "${coordinates_CHRIII[@]}"; do
          line_number_CHRIII=$(awk -v coord="$coordinate_CHRIII" '$3 == coord {print NR}' "$input_file_CHRIII")

          if [[ -n "$line_number_CHRIII" ]]; then
            top_line_CHRIII=$((line_number_CHRIII - offset))
            bottom_line_CHRIII=$((line_number_CHRIII + offset))
            [[ "$top_line_CHRIII" -lt 1 ]] && top_line_CHRIII=1

            top_line_content=$(sed -n "${top_line_CHRIII}p" "$input_file_CHRIII")
            mid_line_content=$(sed -n "${line_number_CHRIII}p" "$input_file_CHRIII")
            bottom_line_content=$(sed -n "${bottom_line_CHRIII}p" "$input_file_CHRIII")

            top_coverage=$(echo "$top_line_content" | awk '{print $2}')
            bottom_coverage=$(echo "$bottom_line_content" | awk '{print $2}')
            baseline_coverage=$(awk -v top="$top_coverage" -v bottom="$bottom_coverage" 'BEGIN {print top + (bottom - top)/2}')

            # Extract fields from mid_line_content
            mid_chr=$(echo "$mid_line_content" | awk '{print $1}')
            mid_coverage=$(echo "$mid_line_content" | awk '{print $2}')
            mid_coordinate=$(echo "$mid_line_content" | awk '{print $3}')

            # Calculate coverage difference (mid - baseline)
            coverage_diff=$(awk -v mid="$mid_coverage" -v base="$baseline_coverage" 'BEGIN {print mid - base}')

            # Build new line with: original chr, diff coverage, and coordinate (tab-separated)
            diff_line=$(echo -e "$mid_chr\t$coverage_diff\t$mid_coordinate")

            echo "CHRIII Coord: $coordinate_CHRIII — Coverage Diff: $coverage_diff"

            output_file_CHRIII="${subdir}/${sample}_${exp}_CHRIII_diff_${coordinate_CHRIII}.tsv"
            {
              echo "$diff_line"
            } > "$output_file_CHRIII"

          else
          echo "Coordinate $coordinate_CHRIII not found in $input_file_CHRIII for $sample $exp."
          fi
        done
    
        # Loop through CHRV coordinates
        for coordinate_CHRV in "${coordinates_CHRV[@]}"; do
          line_number_CHRV=$(awk -v coord="$coordinate_CHRV" '$3 == coord {print NR}' "$input_file_CHRV")

          if [[ -n "$line_number_CHRV" ]]; then
            top_line_CHRV=$((line_number_CHRV - offset))
            bottom_line_CHRV=$((line_number_CHRV + offset))
            [[ "$top_line_CHRV" -lt 1 ]] && top_line_CHRV=1

            top_line_content=$(sed -n "${top_line_CHRV}p" "$input_file_CHRV")
            mid_line_content=$(sed -n "${line_number_CHRV}p" "$input_file_CHRV")
            bottom_line_content=$(sed -n "${bottom_line_CHRV}p" "$input_file_CHRV")

            top_coverage=$(echo "$top_line_content" | awk '{print $2}')
            bottom_coverage=$(echo "$bottom_line_content" | awk '{print $2}')
            baseline_coverage=$(awk -v top="$top_coverage" -v bottom="$bottom_coverage" 'BEGIN {print top + (bottom - top)/2}')

            # Extract fields from mid_line_content
            mid_chr=$(echo "$mid_line_content" | awk '{print $1}')
            mid_coverage=$(echo "$mid_line_content" | awk '{print $2}')
            mid_coordinate=$(echo "$mid_line_content" | awk '{print $3}')

            # Calculate coverage difference (mid - baseline)
            coverage_diff=$(awk -v mid="$mid_coverage" -v base="$baseline_coverage" 'BEGIN {print mid - base}')

            # Build new line with: original chr, diff coverage, and coordinate (tab-separated)
            diff_line=$(echo -e "$mid_chr\t$coverage_diff\t$mid_coordinate")

            echo "CHRV Coord: $coordinate_CHRV — Coverage Diff: $coverage_diff"

            output_file_CHRV="${subdir}/${sample}_${exp}_CHRV_diff_${coordinate_CHRV}.tsv"
            {
              echo "$diff_line"
            } > "$output_file_CHRV"

          else
          echo "Coordinate $coordinate_CHRV not found in $input_file_CHRV for $sample $exp."
          fi
        done
      else
      echo "Files not found for $sample $exp in $subdir"
      fi
    done
  done
done


for strain in "$MYWD"*/; do
  echo "Processing directory: $strain to calculate MATa coverage (r18)" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line
  strain="${strain}"
  root_dir="${strain}"

  # Loop through sample prefixes (T0, T1, T2, etc.)
    R_SCRIPT="SR_process_cov_III_V_18nt.R"
    strain="${strain}"
    root_dir="${strain}"
    echo "Processing strain: $strain" >> "$log_file"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
          continue
        fi  
done


# Move the plots to the Graphs_Coverage folder
for strain in "$MYWD"*/; do
  for sample in TSG; do
    mv "${strain}/plot_${sample}_18nt_MATa_Coverage_Quant.svg" "${strain}/Graphs_Coverage/"
  done
done

# Calulate total elapsed time
elapsed_time_total_cov=$((( SECONDS - start_time_total_cov )/60))
echo "Coverage and Polymorphisms Analysis completed in ${elapsed_time_total_cov} minutes" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line            



# Create a log and stat file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "DISCORDANT ANALYSIS - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line

# Start timer for the entire script processing
#start_time_total_script=$SECONDS
start_time_total_script_2=$SECONDS

########### MODULE CORE - START ###########
# ############## Alignment and processing of 75bp reads ############

# Start timer for the alignment and processing section
start_time_total_alignment=$SECONDS

# Index RG for bowtie alignment
bowtie-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed"

# Index RG for bowtie2 alignment
bowtie2-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed"

# Loop through each directory inside MYWD

echo "================================" >> "$log_file"
echo "### 75bp analysis ###" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line
echo "### Alignments and SAM processing ###" >> "$log_file"
current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Initiated at ${current_time}" >> "$log_file" 
echo "" >> "$log_file"  # Adds a blank line

for strain in "$MYWD"*/; do
  echo "Processing directory: $strain" >> "$log_file"

  # Loop through sample prefixes (T0, TSG, TLG, TLR.)
    for sample in T0 TSG; do
      for experiment in "${EXP_LIST[@]}"; do
        file1_gz="${strain}/${sample}_${experiment}_R1.fastq.gz"
        file2_gz="${strain}/${sample}_${experiment}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz" >> "$log_file"
          echo "" >> "$log_file"  # Adds a blank line

          # Keep the current pair compressed for 18bp alignment
          gunzip -k "$file1_gz" "$file2_gz" # keep compressed
          

          if [[ -f "${strain}/${sample}_${experiment}_R1.fastq" && -f "${strain}/${sample}_${experiment}_R2.fastq" ]]; then
            # Determine the number of cores available
            N_CPU=$(nproc)

            # Start timers for total processing of a strain/sample/experiment
            start_time_total=$SECONDS
        
            # Trim reads using cutadapt
            echo "### $(basename "$strain")/${sample} ${experiment} ###" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line
            start_time=$SECONDS
            # trim R1 reads
            cutadapt -j "$N_CPU" --cut -75 -o "${strain}/${sample}_${experiment}_R1_1.fastq" "${strain}/${sample}_${experiment}_R1.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${strain}/${sample}_${experiment}_R1_2.fastq" "${strain}/${sample}_${experiment}_R1.fastq"
            # trim R2 reads
            cutadapt -j "$N_CPU" --cut -75 -o "${strain}/${sample}_${experiment}_R2_1.fastq" "${strain}/${sample}_${experiment}_R2.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${strain}/${sample}_${experiment}_R2_2.fastq" "${strain}/${sample}_${experiment}_R2.fastq"

            # Remove intermediate 75nt fastq files
            rm "${strain}/${sample}_${experiment}_R1.fastq" "${strain}/${sample}_${experiment}_R2.fastq"

            # Rename them as _rA or _rB # Needs sed -E to rename reads matching V35 or E25
            # sed -E '/^@(V35|E25)[a-zA-Z0-9].*\/1/s/\/1/rA\/1/' "${strain}/${sample}_${experiment}_R1_1.fastq" > "${strain}/${sample}_${experiment}_R1_1_A.fastq"
            # sed -E '/^@(V35|E25)[a-zA-Z0-9].*\/2/s/\/2/rA\/2/' "${strain}/${sample}_${experiment}_R2_1.fastq" > "${strain}/${sample}_${experiment}_R2_1_A.fastq"
            # sed -E '/^@(V35|E25)[a-zA-Z0-9].*\/1/s/\/1/rB\/1/' "${strain}/${sample}_${experiment}_R1_2.fastq" > "${strain}/${sample}_${experiment}_R1_2_B.fastq"
            # sed -E '/^@(V35|E25)[a-zA-Z0-9].*\/2/s/\/2/rB\/2/' "${strain}/${sample}_${experiment}_R2_2.fastq" > "${strain}/${sample}_${experiment}_R2_2_B.fastq"

            # Modified version 11/04/2026: to analyze also Novogene reads and deal with possible problems when splitting reads and getting @ as first quality character
            sed -E '1~4 s/^@(V35|E25|LH)[a-zA-Z0-9].*\/1/&/; 1~4 s/\/1/rA\/1/' "${strain}/${sample}_${experiment}_R1_1.fastq" > "${strain}/${sample}_${experiment}_R1_1_A.fastq"
            sed -E '1~4 s/^@(V35|E25|LH)[a-zA-Z0-9].*\/2/&/; 1~4 s/\/2/rA\/2/' "${strain}/${sample}_${experiment}_R2_1.fastq" > "${strain}/${sample}_${experiment}_R2_1_A.fastq"
            sed -E '1~4 s/^@(V35|E25|LH)[a-zA-Z0-9].*\/1/&/; 1~4 s/\/1/rB\/1/' "${strain}/${sample}_${experiment}_R1_2.fastq" > "${strain}/${sample}_${experiment}_R1_2_B.fastq"
            sed -E '1~4 s/^@(V35|E25|LH)[A-Za-z0-9].*\/2/&/; 1~4 s/\/2/rB\/2/' "${strain}/${sample}_${experiment}_R2_2.fastq" > "${strain}/${sample}_${experiment}_R2_2_B.fastq"


            # Cat _rA and _rB R1 files; and _rA and _rB R2 files
            cat "${strain}/${sample}_${experiment}_R1_1_A.fastq" "${strain}/${sample}_${experiment}_R1_2_B.fastq" > "${strain}/${sample}_${experiment}_r_R1.fastq"
            cat "${strain}/${sample}_${experiment}_R2_1_A.fastq" "${strain}/${sample}_${experiment}_R2_2_B.fastq" > "${strain}/${sample}_${experiment}_r_R2.fastq"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_R1_1.fastq" "${strain}/${sample}_${experiment}_R1_2.fastq" "${strain}/${sample}_${experiment}_R2_1.fastq" "${strain}/${sample}_${experiment}_R2_2.fastq"
            rm "${strain}/${sample}_${experiment}_R1_1_A.fastq" "${strain}/${sample}_${experiment}_R2_1_A.fastq" "${strain}/${sample}_${experiment}_R1_2_B.fastq" "${strain}/${sample}_${experiment}_R2_2_B.fastq"
                    
            # Filter 75nt reads Q30
            fastp \
              -i "${strain}/${sample}_${experiment}_r_R1.fastq" \
              -o "${strain}/${sample}_${experiment}_r_R1_filtered.fastq" \
              -I "${strain}/${sample}_${experiment}_r_R2.fastq" \
              -O "${strain}/${sample}_${experiment}_r_R2_filtered.fastq" \
              -q 30 -u 0 -e 30 \
              --thread "$N_CPU" \
              --html "${strain}/${sample}_${experiment}_75nt.fastq.html" \
              --json "${strain}/${sample}_${experiment}_75nt.fastq.json"
            
            # Remove intermediate 75nt fastq files
            rm "${strain}/${sample}_${experiment}_r_R1.fastq" "${strain}/${sample}_${experiment}_r_R2.fastq"
            
            elapsed_time=$(( SECONDS - start_time ))
            echo "Cutting and Filtering Reads completed in ${elapsed_time} seconds" >> "$log_file"
          
            # Bowtie mapping (SR -m1 -v0) for R1 filtered reads
            start_time=$SECONDS
            echo "### $(basename "$strain")/${sample} 75nt R1 ###" >> "$stats"
            echo "${experiment}" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S "${MYREF}/S_cerevisiae_indexed" "${strain}/${sample}_${experiment}_r_R1_filtered.fastq" > "${strain}/${sample}_${experiment}_r_R1_filtered.sam" 2>> "$stats"
            echo "" >> "$stats"  # Adds a blank line
            elapsed_time=$(( SECONDS - start_time ))
            echo "Bowtie SR alignment 75nt for R1 reads completed in ${elapsed_time} seconds" >> "$log_file"

            # Bowtie mapping (SR -m1 -v0) for R2 filtered reads
            start_time=$SECONDS
            echo "### $(basename "$strain")/${sample} 75nt R2 ###" >> "$stats"
            echo "${experiment}" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S "${MYREF}/S_cerevisiae_indexed" "${strain}/${sample}_${experiment}_r_R2_filtered.fastq" > "${strain}/${sample}_${experiment}_r_R2_filtered.sam" 2>> "$stats"
            echo "" >> "$stats"  # Adds a blank line
            elapsed_time=$(( SECONDS - start_time ))
            echo "Bowtie SR alignment 75nt for R2 reads completed in ${elapsed_time} seconds" >> "$log_file"
                    
            # Select reads aligning for both R1 and R2
            samtools view -F 4 "${strain}/${sample}_${experiment}_r_R1_filtered.sam" > "${strain}/${sample}_${experiment}_r_R1_mapped.sam"
            samtools view -F 4 "${strain}/${sample}_${experiment}_r_R2_filtered.sam" > "${strain}/${sample}_${experiment}_r_R2_mapped.sam"

            # Extract read names, sort and find common reads
            cut -f1 "${strain}/${sample}_${experiment}_r_R1_mapped.sam" | sed 's/\/1//' > "${strain}/${sample}_${experiment}_r_R1_mapped.txt"
            cut -f1 "${strain}/${sample}_${experiment}_r_R2_mapped.sam" | sed 's/\/2//' > "${strain}/${sample}_${experiment}_r_R2_mapped.txt"
            sort "${strain}/${sample}_${experiment}_r_R1_mapped.txt" -o "${strain}/${sample}_${experiment}_r_R1_mapped_sorted.txt"
            sort "${strain}/${sample}_${experiment}_r_R2_mapped.txt" -o "${strain}/${sample}_${experiment}_r_R2_mapped_sorted.txt"

            comm -12 "${strain}/${sample}_${experiment}_r_R1_mapped_sorted.txt" "${strain}/${sample}_${experiment}_r_R2_mapped_sorted.txt" > "${strain}/${sample}_${experiment}_r_R12_mapped.txt"
            
            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_r_R1_filtered.sam" "${strain}/${sample}_${experiment}_r_R2_filtered.sam"
            rm  "${strain}/${sample}_${experiment}_r_R1_mapped.sam" "${strain}/${sample}_${experiment}_r_R2_mapped.sam"
            rm "${strain}/${sample}_${experiment}_r_R1_mapped.txt" "${strain}/${sample}_${experiment}_r_R2_mapped.txt"
            rm "${strain}/${sample}_${experiment}_r_R1_mapped_sorted.txt" "${strain}/${sample}_${experiment}_r_R2_mapped_sorted.txt"
            

            # Bowtie2 mapping (in a forced -m1 -v0 mode)
            start_time=$SECONDS
            echo "### $(basename "$strain")/${sample} 75nt paired-end Bowtie2 alignment ###" >> "$stats"
            echo "${experiment}" >> "$stats"
            bowtie2 \
              -p "$N_CPU" \
              --no-1mm-upfront \
              --score-min C,0,0 \
              -N 0 \
              --end-to-end \
              --fr \
              -x "${MYREF}/S_cerevisiae_indexed" \
              -1 "${strain}/${sample}_${experiment}_r_R1_filtered.fastq" \
              -2 "${strain}/${sample}_${experiment}_r_R2_filtered.fastq" \
              -S "${strain}/${sample}_${experiment}.sam" 2>> "$stats" 

            echo "" >> "$stats"  # Adds a blank line
            elapsed_time=$(( SECONDS - start_time ))
            echo "Bowtie2 alignment 75nt for paired-end reads completed in ${elapsed_time} seconds" >> "$log_file"
            echo "" >> "$log_file"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_r_R1_filtered.fastq"
            rm "${strain}/${sample}_${experiment}_r_R2_filtered.fastq"

            #########
            # Bowtie2 SAM processing (concordant read-pairs for % recombination)
            start_time=$SECONDS
            echo "### $(basename "$strain")/${sample} Bowtie2 SAM processing - concordant read pairs ###" >> "$log_file"
            echo "${experiment}" >> "$log_file"

            # Remove header for processing
            sed -n -e '1,19p' "${strain}/${sample}_${experiment}.sam" > "${strain}/${sample}_${experiment}_header.sam"
            tail -n +20 "${strain}/${sample}_${experiment}.sam" > "${strain}/${sample}_${experiment}_alignment.sam"

            # Processing (set pairs in the same row, extract only those aligning both R1 and R2 completely)
            # Consider for further processing only reads pair aligning uniquely
            awk -vOFS='\t' '{$11="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"; print}' "${strain}/${sample}_${experiment}_alignment.sam" | \
            cut -f1-19 | \
            sed '$!N;s/\n/ /' | \
            awk '($3 != $7 && $7 == "=")' | \
            awk '($7 != "*")' | \
            awk '$6 == "75M"' | \
            awk '$25 == "75M"' | \
            awk '$13 == "XN:i:0"' | \
            awk '$32 == "XN:i:0"' | \
            sed 's/ /\t/g' | \
            awk '($19 != "YT:Z:UP")' | \
            awk '($38 != "YT:Z:UP")' > "${strain}/${sample}_${experiment}_alignment_processed.sam"

            # Remove intermediate files
            #rm "${strain}/${sample}_${experiment}_alignment.sam"

            # Place read pairs in SAM standard output format
            cut -f1-19 "${strain}/${sample}_${experiment}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R1.sam"
            cut -f20-38 "${strain}/${sample}_${experiment}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R2.sam"
            cat "${strain}/${sample}_${experiment}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R2.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R2.sam"

            # Add header back
            cat "${strain}/${sample}_${experiment}_header.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12.sam"

            # Extract R1 reads that aligned in -m1 -v0 in SR bowtie mapping
            samtools view -N "${strain}/${sample}_${experiment}_r_R12_mapped.txt" -o "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Extract R2 reads that aligned in -m1 -v0 in SR bowtie mapping
            samtools view -N "${strain}/${sample}_${experiment}_r_R12_mapped.txt" -o "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Cat mapping reads
            cat "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam"
            
            # Add header back
            cat "${strain}/${sample}_${experiment}_header.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam" > "${strain}/${sample}_${experiment}_concordant_pairs.sam"
            
            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam"

            # Concordant read pairs - unique reads
            awk '!seen[$0]++' "${strain}/${sample}_${experiment}_concordant_pairs.sam" > "${strain}/${sample}_${experiment}_concordant_pairs_unique.sam"

            # Get row count
            tail -n +20 "${strain}/${sample}_${experiment}_concordant_pairs_unique.sam" | wc -l | awk '{print $1}' > "${strain}/${sample}_${experiment}_concordant_pairs_unique_row_count.tsv"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_concordant_pairs.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed.sam"
            rm "${strain}/${sample}_${experiment}_concordant_pairs_unique.sam"
            #rm "${strain}/${sample}_${experiment}_r_R12_mapped.txt"

            echo "" >> "$log_file"  # Adds a blank line
            elapsed_time=$(( SECONDS - start_time ))
            echo "Concordant read pairs processing completed in ${elapsed_time} seconds" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line 
            

            ########

            # Bowtie2 SAM processing (inter-chromosomal discordant read-pairs)
            start_time=$SECONDS
            echo "### $(basename "$strain")/${sample} Bowtie2 SAM processing - inter-chromosomal discordant read pairs ###" >> "$log_file"
            echo "${experiment}" >> "$log_file"

            # Remove header for processing
            #sed -n -e '1,19p' "${strain}/${sample}_${experiment}.sam" > "${strain}/${sample}_${experiment}_header.sam"
            #tail -n +20 "${strain}/${sample}_${experiment}.sam" > "${strain}/${sample}_${experiment}_alignment.sam"

            # Processing (set pairs in the same row, extract only those aligning both R1 and R2 completely)
            # Consider for further processing only reads pair aligning uniquely
            awk -vOFS='\t' '{$11="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"; print}' "${strain}/${sample}_${experiment}_alignment.sam" | \
            cut -f1-19 | \
            sed '$!N;s/\n/ /' | \
            awk '($3 != $7 && $7 != "=")' | \
            awk '($7 != "*")' | \
            awk '$6 == "75M"' | \
            awk '$25 == "75M"' | \
            awk '$13 == "XN:i:0"' | \
            awk '$32 == "XN:i:0"' | \
            sed 's/ /\t/g' | \
            awk '($19 != "YT:Z:UP")' | \
            awk '($38 != "YT:Z:UP")' > "${strain}/${sample}_${experiment}_alignment_processed.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment.sam"

            # Place read pairs in SAM standard output format
            cut -f1-19 "${strain}/${sample}_${experiment}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R1.sam"
            cut -f20-38 "${strain}/${sample}_${experiment}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R2.sam"
            cat "${strain}/${sample}_${experiment}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R2.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R2.sam"

            # Add header back
            cat "${strain}/${sample}_${experiment}_header.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12.sam"

            # Extract R1 reads that aligned in -m1 -v0 in SR bowtie mapping
            samtools view -N "${strain}/${sample}_${experiment}_r_R12_mapped.txt" -o "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Extract R2 reads that aligned in -m1 -v0 in SR bowtie mapping
            samtools view -N "${strain}/${sample}_${experiment}_r_R12_mapped.txt" -o "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"

            # Cat mapping reads
            cat "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam" > "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam"
            
            # Add header back
            cat "${strain}/${sample}_${experiment}_header.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs.sam"
            
            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_header.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R12.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_alignment_processed_R12_header_R2.sam"

            # Inter-chromosomal discordant read pairs - unique reads
            awk '!seen[$0]++' "${strain}/${sample}_${experiment}_inter_discordant_pairs.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam"

            # Remove intermediate files
            rm "${strain}/${sample}_${experiment}_inter_discordant_pairs.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed_R12_header.sam"
            rm "${strain}/${sample}_${experiment}_alignment_processed.sam"
            rm "${strain}/${sample}_${experiment}_r_R12_mapped.txt"
            rm "${strain}/${sample}_${experiment}.sam"
            rm "${strain}/${sample}_${experiment}_header.sam"

            # Prepare tsv file for R processing
            tail -n +20 "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" | \
            # Extract relevant columns (1, 3, 4, 7, 8, 10) and convert to tsv format
            ### Add sam flag!!!!!!
            # Note: $1 is read name, $3 is reference sequence name, $4 is position, $7 is mate reference sequence name, $8 is mate position, $10 is sequence
            awk 'BEGIN{OFS="\t"} {print $1, $3, $4, $7, $8, $10}' > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.tsv"
            
            echo "" >> "$log_file"  # Adds a blank line
            elapsed_time=$(( SECONDS - start_time ))
            echo "Inter-chromosomal discordant read pairs processing completed in ${elapsed_time} seconds" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line 

            # Calculate total elapsed time
            elapsed_time_total=$((( SECONDS - start_time_total )/60))
            echo "Total processing completed in ${elapsed_time_total} minutes" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line 

          else
          echo "Warning: Decompressed files missing for sample $sample in $strain!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $strain!" >> "$log_file"
        echo "" >> "$log_file"
        fi
      done
    done
done

# Calculate alignment and processing total elapsed time
elapsed_time_total_alignment=$((( SECONDS - start_time_total_alignment )/60))
echo "================================" >> "$log_file"
echo "" >> "$log_file"
echo "ALIGNMENT AND SAM PROCESSING COMPLETED IN ${elapsed_time_total_alignment} MINUTES" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line


########### MODULE CORE - END ###########


##### MODULE MATs - START #####
############## MATa-MATa' analysis of 75bp reads ############

# MATa-MATa' analysis

echo "================================" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line
echo "### MATa-MATa' analysis, 75bp analysis ###" >> "$log_file"
current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Initiated at ${current_time}" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line 
start_time_total_MATs=$SECONDS

# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
  for sample in T0 TSG; do
    for experiment in "${EXP_LIST[@]}"; do
      file_alignment="${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam"
      if [[ -f "$file_alignment"  ]]; then
        echo "$(basename "$strain") ${sample} ${experiment}" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line
        echo "Processing MATs for $file_alignment" >> "$log_file" 
        start_time_MATs=$SECONDS
        
        # Determine the number of cores available
        N_CPU=$(nproc)
        
        # Extract inter-chromosomal discordant read pairs for MATa-MATa' analysis
        # Remove header for processing
        sed -n -e '1,19p' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam"

        # Extract reads and cat them to a new file
        # These positions include all the MATa' region, but now it is needed to ensure the read is mapping the last polymorphism
        # awk ' ($3=="CHRIII" && $7=="CHRV" && $8>289178 && $8<290483) ' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam"
        # awk ' ($3=="CHRV" && $7=="CHRIII" && $4>289178 && $4<290483) ' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam"
        awk ' ($3=="CHRIII" && $7=="CHRV" && $8>289191 && $8<290473) ' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam"
        awk ' ($3=="CHRV" && $7=="CHRIII" && $4>289191 && $4<290473) ' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam"

        cat "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.sam"
        #cat "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.tsv"
        #rm  "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam"
        #rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam"
        #rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam"

        # convert SAM to sorted BAM (75nt)
        start_time=$SECONDS
        samtools sort -@ "$N_CPU" -o "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.sam"
        samtools index "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bai"
        elapsed_time=$(( SECONDS - start_time ))
        echo "Bam and Bai 75nt MAT reads completed in ${elapsed_time} seconds" >> "$log_file"

        # Generate BedGraphs coverage files (75nt)
        start_time=$SECONDS
        bamCoverage -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" -o "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bedgraph" -of bedgraph -p "$N_CPU"  -bs 1 --smoothLength 1
        elapsed_time=$(( SECONDS - start_time ))
        echo "Bedgraphs 75nt reads completed in ${elapsed_time} seconds" >> "$log_file"

        # Sorting Bedgraphs files (75nt)
        samtools faidx "${MYREF}/RG_PMV_v9.fasta" # Create index file
        cut -f1,2 "${MYREF}/RG_PMV_v9.fasta.fai" > "${MYREF}/chrom_order.txt"
        bedtools sort -i "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bedgraph" -g "${MYREF}/chrom_order.txt" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_sorted.bedgraph"
             
        
        # Generate TSV files (75nt)
        start_time=$SECONDS
        #bedtools coverage -a "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bedgraph" -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" -d > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.tsv"
        bedtools coverage -a "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_sorted.bedgraph" -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_sorted.tsv"
            
        # Keep only coverage for chromosomes CHRIII and CHRV
        awk '$1=="CHRIII" || $1=="CHRV"' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_sorted.tsv" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_filtered.tsv"

        # Remove intermediate files   
        rm "${strain}/${sample}_${experiment}_"*.bai
        rm "${strain}/${sample}_${experiment}_"*.bam
        rm "${strain}/${sample}_${experiment}_"*.bedgraph
        rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_sorted.tsv"
        rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R1.sam"
        rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_R2.sam"
        rm "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam"

      # Calculate elapsed time
        elapsed_time=$((( SECONDS - start_time_MATs )))
        echo "Total MATs SAM processing completed in ${elapsed_time} seconds" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line 
      else
      echo "Missing files for $strain/$sample/$experiment: $file_alignment" >> "$log_file"
      echo "" >> "$log_file"
      fi
    done
  done
done


# R plots for MATa-MATa' coverage (from inter-chromosomal discordant read pairs)
# Start timer for R processing

R_SCRIPT="DISC_plot_MATa_cov.R"

# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
  echo "Processing directory: ${strain}" >> "$log_file"
      root_dir="${strain}"
      #echo "$root_dir"
        echo "$(basename "$strain")" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line
        echo "Plotting MATa-MATa' coverage" >> "$log_file"
        start_time=$SECONDS
        
        if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
        continue
        fi

      # Calculate elapsed time
        elapsed_time=$((( SECONDS - start_time )/60))
        echo "Total R processing completed in ${elapsed_time} minutes" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line 

done

# Calculate total elapsed time
elapsed_time_total=$((( SECONDS - start_time_total_MATs )/60))
echo "================================" >> "$log_file"
echo "" >> "$log_file"
echo "TOTAL MATa-MATa' PROCESSING COMPLETED IN ${elapsed_time_total} MINUTES" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line    


############## MATa-MATa' analysis of 18bp reads ############

# MATa-MATa' analysis

echo "================================" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line
echo "### MATa-MATa' analysis, 18bp analysis ###" >> "$log_file"
current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Initiated at ${current_time}" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line 
start_time_total_MATs_18=$SECONDS

# Start timer for the alignment and processing section
start_time_total_alignment=$SECONDS

# Index RG for bowtie alignment
bowtie-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed"

# Index RG for bowtie2 alignment
bowtie2-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed"

# Loop through each directory inside MYWD

echo "### Alignments and SAM processing ###" >> "$log_file"
echo "Initiated at ${current_time}" >> "$log_file" 
echo "" >> "$log_file"  # Adds a blank line

# Define the pairs
declare -a R1_ids=("R1_1_1_1" "R1_1_1_2" "R1_1_2_1" "R1_1_2_2" "R1_2_1_1" "R2_1_1_1" "R2_1_1_2" "R2_1_2_1" "R2_1_2_2" "R2_2_1_1")
declare -a R2_ids=("R1_1_2_2" "R1_2_1_1" "R1_2_1_2" "R1_2_2_1" "R1_2_2_2" "R2_1_2_2" "R2_2_1_1" "R2_2_1_2" "R2_2_2_1" "R2_2_2_2")


for strain in "$MYWD"*/; do
  echo "Processing directory: $strain" >> "$log_file"

  # Loop through sample prefixes (TLG)
    for sample in TSG; do
      for experiment in "${EXP_LIST[@]}"; do
        file1_gz="${strain}/${sample}_${experiment}_R1.fastq.gz"
        file2_gz="${strain}/${sample}_${experiment}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz" >> "$log_file"
          echo "" >> "$log_file"  # Adds a blank line

          # Keep the current pair compressed
          gunzip -k "$file1_gz" "$file2_gz"
          #file1_path="${strain}/${sample}_${experiment}_R1.fastq"
          #file2_path="${strain}/${sample}_${experiment}_R2.fastq"

          if [[ -f "${strain}/${sample}_${experiment}_R1.fastq" && -f "${strain}/${sample}_${experiment}_R2.fastq" ]]; then
            # Determine the number of cores available
            N_CPU=$(nproc)

            # Start timers for total processing of a strain/sample/experiment
            start_time_total=$SECONDS
        
            # Trim reads using cutadapt
            echo "### $(basename "$strain")/${sample} ${experiment} ###" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line
            start_time=$SECONDS

            ### 75 nt reads #################################################################################################################

            # trim R1 reads
            cutadapt -j "$N_CPU" --cut -75 -o "${strain}/${sample}_${experiment}_R1_1.fastq" "${strain}/${sample}_${experiment}_R1.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${strain}/${sample}_${experiment}_R1_2.fastq" "${strain}/${sample}_${experiment}_R1.fastq"
            # trim R2 reads
            cutadapt -j "$N_CPU" --cut -75 -o "${strain}/${sample}_${experiment}_R2_1.fastq" "${strain}/${sample}_${experiment}_R2.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${strain}/${sample}_${experiment}_R2_2.fastq" "${strain}/${sample}_${experiment}_R2.fastq"

            # Remove intermediate fastq files
            rm "${strain}/${sample}_${experiment}_R1.fastq" "${strain}/${sample}_${experiment}_R2.fastq"

            ### 37 nt reads #################################################################################################################

            # trim R1 reads
            cutadapt -j "$N_CPU" --cut -38 -o "${strain}/${sample}_${experiment}_R1_1_1.fastq" "${strain}/${sample}_${experiment}_R1_1.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${strain}/${sample}_${experiment}_R1_1_2.fastq" "${strain}/${sample}_${experiment}_R1_1.fastq"

            cutadapt -j "$N_CPU" --cut -38 -o "${strain}/${sample}_${experiment}_R1_2_1.fastq" "${strain}/${sample}_${experiment}_R1_2.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${strain}/${sample}_${experiment}_R1_2_2.fastq" "${strain}/${sample}_${experiment}_R1_2.fastq"

            # trim R2 reads
            cutadapt -j "$N_CPU" --cut -38 -o "${strain}/${sample}_${experiment}_R2_1_1.fastq" "${strain}/${sample}_${experiment}_R2_1.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${strain}/${sample}_${experiment}_R2_1_2.fastq" "${strain}/${sample}_${experiment}_R2_1.fastq"

            cutadapt -j "$N_CPU" --cut -38 -o "${strain}/${sample}_${experiment}_R2_2_1.fastq" "${strain}/${sample}_${experiment}_R2_2.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${strain}/${sample}_${experiment}_R2_2_2.fastq" "${strain}/${sample}_${experiment}_R2_2.fastq"
          

            # Remove intermediate fastq files
            rm "${strain}/${sample}_${experiment}_R1_1.fastq" "${strain}/${sample}_${experiment}_R1_2.fastq" 
            rm "${strain}/${sample}_${experiment}_R2_1.fastq" "${strain}/${sample}_${experiment}_R2_2.fastq"


            ### 18 nt reads #################################################################################################################

            # trim R1 reads
            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R1_1_1_1.fastq" "${strain}/${sample}_${experiment}_R1_1_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R1_1_1_2.fastq" "${strain}/${sample}_${experiment}_R1_1_1.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R1_1_2_1.fastq" "${strain}/${sample}_${experiment}_R1_1_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R1_1_2_2.fastq" "${strain}/${sample}_${experiment}_R1_1_2.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R1_2_1_1.fastq" "${strain}/${sample}_${experiment}_R1_2_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R1_2_1_2.fastq" "${strain}/${sample}_${experiment}_R1_2_1.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R1_2_2_1.fastq" "${strain}/${sample}_${experiment}_R1_2_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R1_2_2_2.fastq" "${strain}/${sample}_${experiment}_R1_2_2.fastq"

            # trim R2 reads
            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R2_1_1_1.fastq" "${strain}/${sample}_${experiment}_R2_1_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R2_1_1_2.fastq" "${strain}/${sample}_${experiment}_R2_1_1.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R2_1_2_1.fastq" "${strain}/${sample}_${experiment}_R2_1_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R2_1_2_2.fastq" "${strain}/${sample}_${experiment}_R2_1_2.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R2_2_1_1.fastq" "${strain}/${sample}_${experiment}_R2_2_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R2_2_1_2.fastq" "${strain}/${sample}_${experiment}_R2_2_1.fastq"

            cutadapt -j "$N_CPU" --cut -19 -o "${strain}/${sample}_${experiment}_R2_2_2_1.fastq" "${strain}/${sample}_${experiment}_R2_2_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${strain}/${sample}_${experiment}_R2_2_2_2.fastq" "${strain}/${sample}_${experiment}_R2_2_2.fastq"

            # Remove intermediate fastq files
            rm "${strain}/${sample}_${experiment}_R1_1_1.fastq" "${strain}/${sample}_${experiment}_R1_1_2.fastq"
            rm "${strain}/${sample}_${experiment}_R1_2_1.fastq" "${strain}/${sample}_${experiment}_R1_2_2.fastq"
            rm "${strain}/${sample}_${experiment}_R2_1_1.fastq" "${strain}/${sample}_${experiment}_R2_1_2.fastq"
            rm "${strain}/${sample}_${experiment}_R2_2_1.fastq" "${strain}/${sample}_${experiment}_R2_2_2.fastq"

            for i in "${!R1_ids[@]}"; do
              R1_file=${R1_ids[$i]}
              R2_file=${R2_ids[$i]}
              echo "Processing files: "${strain}/${sample}_${experiment}_${R1_file}.fastq" "${strain}/${sample}_${experiment}_${R2_file}.fastq"" >> "$log_file"
              echo "" >> "$log_file"

               # Filter 18nt reads Q30
              fastp \
                -i "${strain}/${sample}_${experiment}_${R1_file}.fastq" \
                -o "${strain}/${sample}_${experiment}_${R1_file}_filtered.fastq" \
                -I "${strain}/${sample}_${experiment}_${R2_file}.fastq" \
                -O "${strain}/${sample}_${experiment}_${R2_file}_filtered.fastq" \
                -q 30 -u 0 -e 30 \
                --thread "$N_CPU" \
                --html "${strain}/${sample}_${experiment}_${R1_file}${R2_file}_18nt.fastq.html" \
                --json "${strain}/${sample}_${experiment}_${R1_file}${R2_file}_18nt.fastq.json"
              
              
              elapsed_time=$(( SECONDS - start_time ))
              echo "Cutting and Filtering Reads completed in ${elapsed_time} seconds" >> "$log_file"
              echo ""  >> "$log_file"

                # Bowtie mapping (SR -m1 -v0) for R1 filtered reads
              start_time=$SECONDS
              echo "### $(basename "$strain")/${sample} 18nt R1 ###" >> "$stats"
              echo "${experiment}" >> "$stats"
              echo "${R1_file}" >> "$stats"
              bowtie -p "$N_CPU" -m 1 -v 0 -S "${MYREF}/S_cerevisiae_indexed" "${strain}/${sample}_${experiment}_${R1_file}_filtered.fastq" > "${strain}/${sample}_${experiment}_${R1_file}_filtered.sam" 2>> "$stats"
              echo "" >> "$stats"  # Adds a blank line
              elapsed_time=$(( SECONDS - start_time ))
              echo "Bowtie SR alignment 18nt for R1 reads completed in ${elapsed_time} seconds" >> "$log_file"
              echo "" >> "$log_file"

              # Bowtie mapping (SR -m1 -v0) for R2 filtered reads
              start_time=$SECONDS
              echo "### $(basename "$strain")/${sample} 18nt R2 ###" >> "$stats"
              echo "${experiment}" >> "$stats"
              echo "${R2_file}" >> "$stats"
              bowtie -p "$N_CPU" -m 1 -v 0 -S "${MYREF}/S_cerevisiae_indexed" "${strain}/${sample}_${experiment}_${R2_file}_filtered.fastq" > "${strain}/${sample}_${experiment}_${R2_file}_filtered.sam" 2>> "$stats"
              echo "" >> "$stats"  # Adds a blank line
              elapsed_time=$(( SECONDS - start_time ))
              echo "Bowtie SR alignment 18nt for R2 reads completed in ${elapsed_time} seconds" >> "$log_file"
              echo "" >> "$log_file"
                    
              # Select reads aligning for both R1 and R2
              samtools view -F 4 "${strain}/${sample}_${experiment}_${R1_file}_filtered.sam" > "${strain}/${sample}_${experiment}_${R1_file}_mapped.sam"
              samtools view -F 4 "${strain}/${sample}_${experiment}_${R2_file}_filtered.sam" > "${strain}/${sample}_${experiment}_${R2_file}_mapped.sam"

              # Extract read names, sort and find common reads
              cut -f1 "${strain}/${sample}_${experiment}_${R1_file}_mapped.sam" | sed 's/\/[12]//' > "${strain}/${sample}_${experiment}_${R1_file}_mapped.txt"
              cut -f1 "${strain}/${sample}_${experiment}_${R2_file}_mapped.sam" | sed 's/\/[12]//' > "${strain}/${sample}_${experiment}_${R2_file}_mapped.txt"
              sort "${strain}/${sample}_${experiment}_${R1_file}_mapped.txt" -o "${strain}/${sample}_${experiment}_${R1_file}_mapped_sorted.txt"
              sort "${strain}/${sample}_${experiment}_${R2_file}_mapped.txt" -o "${strain}/${sample}_${experiment}_${R2_file}_mapped_sorted.txt"

              comm -12 "${strain}/${sample}_${experiment}_${R1_file}_mapped_sorted.txt" "${strain}/${sample}_${experiment}_${R2_file}_mapped_sorted.txt" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_mapped.txt"
            
              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_filtered.sam" "${strain}/${sample}_${experiment}_${R2_file}_filtered.sam"
              rm  "${strain}/${sample}_${experiment}_${R1_file}_mapped.sam" "${strain}/${sample}_${experiment}_${R2_file}_mapped.sam"
              rm "${strain}/${sample}_${experiment}_${R1_file}_mapped.txt" "${strain}/${sample}_${experiment}_${R2_file}_mapped.txt"
              rm "${strain}/${sample}_${experiment}_${R1_file}_mapped_sorted.txt" "${strain}/${sample}_${experiment}_${R2_file}_mapped_sorted.txt"
            

              # Bowtie2 mapping (in a forced -m1 -v0 mode)
              start_time=$SECONDS
              echo "### $(basename "$strain")/${sample} 18nt paired-end Bowtie2 alignment ###" >> "$stats"
              echo "${experiment}" >> "$stats"
              echo "${R1_file} and ${R2_file}" >> "$stats"
              bowtie2 \
                -p "$N_CPU" \
                --no-1mm-upfront \
                --score-min C,0,0 \
                -N 0 \
                --end-to-end \
                --fr \
                -x "${MYREF}/S_cerevisiae_indexed" \
                -1 "${strain}/${sample}_${experiment}_${R1_file}_filtered.fastq" \
                -2 "${strain}/${sample}_${experiment}_${R2_file}_filtered.fastq" \
                -S "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}.sam" 2>> "$stats" 

              echo "" >> "$stats"  # Adds a blank line
              elapsed_time=$(( SECONDS - start_time ))
              echo "Bowtie2 alignment 18nt for paired-end reads completed in ${elapsed_time} seconds" >> "$log_file"
              echo "" >> "$log_file"

              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_filtered.fastq"
              rm "${strain}/${sample}_${experiment}_${R2_file}_filtered.fastq"

              # Bowtie2 SAM processing (inter-chromosomal discordant read-pairs)
              start_time=$SECONDS
              echo "### $(basename "$strain")/${sample} Bowtie2 SAM processing - inter-chromosomal discordant read pairs ###" >> "$log_file"
              echo "${experiment}" >> "$log_file"
              echo "${R1_file} and ${R2_file}" >> "$log_file"

              # Remove header for processing
              sed -n -e '1,19p' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_header.sam"
              tail -n +20 "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment.sam"

              # Processing (set pairs in the same row, extract only those aligning both R1 and R2 completely)
              # Consider for further processing only reads pair aligning uniquely
              awk -vOFS='\t' '{$11="AAAAAAAAAAAAAAAAAA"; print}' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment.sam" | \
              cut -f1-19 | \
              sed '$!N;s/\n/ /' | \
              awk '($3 != $7 && $7 != "=")' | \
              awk '($7 != "*")' | \
              awk '$6 == "18M"' | \
              awk '$25 == "18M"' | \
              awk '$13 == "XN:i:0"' | \
              awk '$32 == "XN:i:0"' | \
              sed 's/ /\t/g' | \
              awk '($19 != "YT:Z:UP")' | \
              awk '($38 != "YT:Z:UP")' > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed.sam"

              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment.sam"

              # Place read pairs in SAM standard output format
              cut -f1-19 "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R1.sam"
              cut -f20-38 "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R2.sam"
              cat "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R2.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12.sam"

              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R1.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R2.sam"

              # Add header back
              cat "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_header.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header.sam"

              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12.sam"

              # Extract R1 reads that aligned in -m1 -v0 in SR bowtie mapping
              samtools view -N "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_mapped.txt" -o "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header.sam"

              # Extract R2 reads that aligned in -m1 -v0 in SR bowtie mapping
              samtools view -N "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_mapped.txt" -o "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R2.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header.sam"

              # Cat mapping reads
              cat "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R2.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R12.sam"
            
              # Add header back
              cat "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_header.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R12.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs.sam"
              
              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_header.sam" 
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R12.sam"
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R1.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header_R2.sam"

              # Inter-chromosomal discordant read pairs - unique reads
              awk '!seen[$0]++' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique.sam"

              # Remove intermediate files
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs.sam"
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed_R12_header.sam"
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_alignment_processed.sam"
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_mapped.txt"
              rm "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}.sam"

              # Extract discordant read pairs for MATa-MATa'
              sed -n -e '1,19p' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam"
              awk ' ($3=="CHRIII" && $7=="CHRV" && $8>289178 && $8<290483) ' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique_R1_MAT.sam"
              awk ' ($3=="CHRV" && $7=="CHRIII" && $4>289178 && $4<290483) ' "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique_R2_MAT.sam"
              cat "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique_R1_MAT.sam" "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique_R2_MAT.sam" > "${strain}/${sample}_${experiment}_${R1_file}_${R2_file}_inter_discordant_pairs_unique_MAT_r18.sam"

            
              echo "" >> "$log_file"  # Adds a blank line
              elapsed_time=$(( SECONDS - start_time ))
              echo "Inter-chromosomal discordant read pairs processing completed in ${elapsed_time} seconds" >> "$log_file"
              echo "" >> "$log_file"  # Adds a blank line 

          

            done
            # Calculate elapsed time
            elapsed_time=$((( SECONDS - start_time_total )))
            echo "Total MATs processing completed in ${elapsed_time} seconds" >> "$log_file"
            echo "" >> "$log_file"  # Adds a blank line 

            rm -f ${strain}/${sample}_${experiment}_*.fastq
            cat ${strain}/${sample}_${experiment}_*_inter_discordant_pairs_unique_MAT_r18.sam > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_noheader_r18.sam"
            #combined_file="${strain}/${sample}_${experiment}_MAT_noheader.sam"
            #find "${strain}" -name '*_inter_discordant_pairs_unique_MAT.sam' -print0 | xargs -0 cat > "$combined_file"
            cat "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_header.sam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_noheader_r18.sam" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.sam"

            #####
            rm -f ${strain}/${sample}_${experiment}_*_pairs_unique.sam
            rm -f ${strain}/${sample}_${experiment}_*_pairs_unique_R1.sam
            rm -f ${strain}/${sample}_${experiment}_*_pairs_unique_R2.sam
            rm -f ${strain}/${sample}_${experiment}_*_unique_header.sam
            rm -f ${strain}/${sample}_${experiment}_*_pairs_unique_R2.sam
            rm -f ${strain}/${sample}_${experiment}_*_unique_MAT_noheader_r18.sam
            ###### remove this too
            rm -f ${strain}/${sample}_${experiment}_R*_MAT.sam
            rm -f ${strain}/${sample}_${experiment}_*_header.sam
            rm -f ${strain}/${sample}_${experiment}_*_noheader_r18.sam
            rm -f ${strain}/${sample}_${experiment}_R*_unique.sam

          else
          echo "Warning: Decompressed files missing for sample $sample in $strain!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $strain!" >> "$log_file"
        echo "" >> "$log_file"
        fi
        
      done
    done
done



#Coverage for MATa-MATa' discordant read pairs

# MATa-MATa' analysis


# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
  for sample in TSG; do
    for experiment in "${EXP_LIST[@]}"; do
      file_alignment="${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.sam"
      if [[ -f "$file_alignment"  ]]; then
        echo "$(basename "$strain") ${sample} ${experiment}" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line
        echo "Processing MATs for $file_alignment" >> "$log_file" 
        start_time_MATs=$SECONDS
        
        # Determine the number of cores available
        N_CPU=$(nproc)
        
        # convert SAM to sorted BAM (75nt)
        start_time=$SECONDS
        samtools sort -@ "$N_CPU" -o "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.sam"
        samtools index "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bam" "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bai"
        elapsed_time=$(( SECONDS - start_time ))
        echo "Bam and Bai 18nt MAT reads completed in ${elapsed_time} seconds" >> "$log_file"

        # Generate BedGraphs coverage files (75nt)
        start_time=$SECONDS
        bamCoverage -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bam" -o "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bedgraph" -of bedgraph -p "$N_CPU"  -bs 1 --smoothLength 1
        elapsed_time=$(( SECONDS - start_time ))
        echo "Bedgraphs 18nt reads completed in ${elapsed_time} seconds" >> "$log_file"

        # Sorting Bedgraphs files (75nt)
        samtools faidx "${MYREF}/RG_PMV_v9.fasta" # Create index file
        cut -f1,2 "${MYREF}/RG_PMV_v9.fasta.fai" > "${MYREF}/chrom_order.txt"
        bedtools sort -i "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bedgraph" -g "${MYREF}/chrom_order.txt" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18_sorted.bedgraph"
             
        
        # Generate TSV files (75nt)
        start_time=$SECONDS
        #bedtools coverage -a "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bedgraph" -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.bam" -d > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT.tsv"
        bedtools coverage -a "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18_sorted.bedgraph" -b "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18_sorted.tsv"
            
        # Keep only coverage for chromosomes CHRIII and CHRV
        awk '$1=="CHRIII" || $1=="CHRV"' "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18_sorted.tsv" > "${strain}/${sample}_${experiment}_inter_discordant_pairs_unique_MAT_complete_r18_filtered.tsv"

        # Remove intermediate files   
        rm "${strain}/${sample}_${experiment}_"*.bai
        rm "${strain}/${sample}_${experiment}_"*.bam
        rm "${strain}/${sample}_${experiment}_"*.bedgraph
        rm -f ${strain}/${sample}_${experiment}_*_MAT_complete_r18_sorted.tsv
       

      # Calculate elapsed time
        elapsed_time=$((( SECONDS - start_time_MATs )))
        echo "Total MATs processing completed in ${elapsed_time} seconds" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line 
      else
      echo "Missing files for $strain/$sample/$experiment: $file_alignment" >> "$log_file"
      echo "" >> "$log_file"
      fi
    done
  done
done

# elapsed_time_total=$(( SECONDS - start_time ))
# echo "Inter-chromosomal discordant read pairs R processing completed in ${elapsed_time} seconds" >> "$log_file"

# Calculate total elapsed time
elapsed_time_total=$((( SECONDS - start_time_total_MATs_18 )/60))
echo "Total MATs processing completed in ${elapsed_time_total} minutes" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line  



# R plots for MATa-MATa' discordant read pairs

R_SCRIPT="DISC_plot_MATa_cov_r18.R"

# Start timer for R processing
# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
  echo "Processing directory: ${strain}" >> "$log_file"
      root_dir="${strain}"
      #echo "$root_dir"
        echo "$(basename "$strain")" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line
        echo "Plotting MATa-MATa' coverage" >> "$log_file"
        start_time=$SECONDS
        
        if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
        continue
        fi


      # Calculate elapsed time
        elapsed_time=$((( SECONDS - start_time )))
        echo "Total R processing completed in ${elapsed_time} seconds" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line 

done

# Calculate alignment and processing total elapsed time
elapsed_time_total_r18=$((( SECONDS - start_time_total_MATs_18 )/60))
echo "================================" >> "$log_file"
echo "" >> "$log_file"
echo "ALIGNMENT AND SAM PROCESSING COMPLETED IN ${elapsed_time_total_r18} MINUTES" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line


##### MODULE MATs - DATA ORGANIZATION #####
# Move data into subfolders
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/Discordant_alignments" "${subdir}/Discordant_MAT_analysis"
  mkdir -p "${subdir}/Discordant_alignments/FASTQP_75nt" "${subdir}/Discordant_alignments/FASTQP_18nt" "${subdir}/Discordant_alignments/SAM_75nt" "${subdir}/Discordant_alignments/SAM_18nt" 
  mkdir -p "${subdir}/Discordant_MAT_analysis/MAT_Data_75nt" "${subdir}/Discordant_MAT_analysis/MAT_Plots_75nt" "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt" "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt" 
  
  mv "${subdir}"/*_75nt.fastq.html "${subdir}/Discordant_alignments/FASTQP_75nt/" 2> /dev/null
  mv "${subdir}"/*_75nt.fastq.json "${subdir}/Discordant_alignments/FASTQP_75nt/" 2> /dev/null
  mv "${subdir}"/*_18nt.fastq.html "${subdir}/Discordant_alignments/FASTQP_18nt/" 2> /dev/null
  mv "${subdir}"/*_18nt.fastq.json "${subdir}/Discordant_alignments/FASTQP_18nt/" 2> /dev/null

  mv "${subdir}"/*_inter_discordant_pairs_unique_MAT_filtered.tsv "${subdir}/Discordant_alignments/SAM_75nt/" 2> /dev/null
  mv "${subdir}"/*_inter_discordant_pairs_unique_MAT.sam "${subdir}/Discordant_alignments/SAM_75nt/" 2> /dev/null

  mv "${subdir}"/*_inter_discordant_pairs_unique_MAT_complete_r18_filtered.tsv "${subdir}/Discordant_alignments/SAM_18nt/" 2> /dev/null
  mv "${subdir}"/*_inter_discordant_pairs_unique_MAT_complete_r18.sam "${subdir}/Discordant_alignments/SAM_18nt/" 2> /dev/null
  mv "${subdir}"/*_inter_discordant_pairs_unique_MAT_r18.sam "${subdir}/Discordant_alignments/SAM_18nt/" 2> /dev/null

  mv "${subdir}"/*_MAT_coverage_r18_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_count_HOinc_reads_summary_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_count_total_reads_summary_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_GC_CO_summary_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_groups_summary_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_r18_processed_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_18nt/" 2> /dev/null

  mv "${subdir}"/MATa_MATa_GC_CO_r18_*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt/" 2> /dev/null
  mv "${subdir}"/MATa_MATa_GC_group_r18_*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt/" 2> /dev/null
  mv "${subdir}"/MATa_MATa_pairs_r18_*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt/" 2> /dev/null
  mv "${subdir}"/MATa_MATa_poly_*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt/" 2> /dev/null
  mv "${subdir}"/Average_MATa_MATa_coverage_r18*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_18nt/" 2> /dev/null

  mv "${subdir}"/*_MAT_coverage_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_75nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_75nt/" 2> /dev/null
  mv "${subdir}"/*_MAT_pairs_summary_df.tsv "${subdir}/Discordant_MAT_analysis/MAT_Data_75nt/" 2> /dev/null

  mv "${subdir}"/Average_MATa_MATa_coverage_*.svg "${subdir}/Discordant_MAT_analysis/MAT_Plots_75nt/" 2> /dev/null
  mv "${subdir}"/MATa_MATa_pairs_*.svg  "${subdir}/Discordant_MAT_analysis/MAT_Plots_75nt/" 2> /dev/null

done
  

##### MODULE MATs - END #####