#!/bin/bash

AUTHORS="Lydia Iglesias, Narciso M. Quijada, Andrés Clemente-Blanco"
LASTMODIF="2026-04-24"
VERSION="0.4"
MODIFICATIONS="experiment name dynamically set, COMPLETE, validation 10kb"


DiGRAPH=$0
while [ -h "$DiGRAPH" ]; do # resolve $DiGRAPH until the file is no longer a symlink
  DiGRAPHDIR="$( cd -P "$( dirname "$0" )" && pwd )"
  DiGRAPH="$(readlink "$DiGRAPH")"
  [[ $DiGRAPH != /* ]] && DiGRAPH="$DiGRAPHDIR/$DiGRAPH" # if $DiGRAPH is a symlink, resolve it relative to the path where the symlink file was located
done
DiGRAPHDIR="$( cd -P "$( dirname "$DiGRAPH" )" && pwd )"

# WORKING VARIABLES
CATEGORY_PATH=
MYBLAST=
MYREF=
MYREPORT=
MYWD=
MYSCRIPTS=
STRAIN_REF="no"
NUMBER_EXP=3
N_CPU=$(nproc)
#N_CPU=$(sysctl -n hw.ncpu) #macOS

current_time=
log_file=
stats=

#MYREF=/home/ibfg/GWSL/RG # Replace with the path to your MYREF directory: path/to/RG
#MYWD=/home/ibfg/GWSL/WD/ # Replace with the path to your MYWD directory: path/to/WD
#CATEGORY_PATH=/home/ibfg/GWSL/Categories # Replace with the path to your CATEGORY_PATH directory: path/to/Categories
#MYBLAST=/home/ibfg/GWSL/BLAST/features_extraction # Replace with the path to your MYBLAST directory: path/to/BLAST
#MYREPORT=/home/ibfg/GWSL/Report_files # Replace with the path to your MYREPORT directory: path/to/Report_files

# Message colors
COL_RESET=$(tput sgr 0)
COL_blue=$(tput setaf 4)
COL_cyan=$(tput setaf 6)
COL_green=$(tput setaf 2)
COL_magenta=$(tput setaf 5)
COL_purple=$(tput setaf 5)
COL_red=$(tput setaf 1)
COL_white=$(tput setaf 7)
COL_yellow=$(tput setaf 3)

usage () {

cat << EOF

=============================================================

██████╗               ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗
██╔══██╗  ██╗        ██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║
██║  ██║  ╚═╝  ███╗  ██║  ███╗██████╔╝███████║██████╔╝███████║  
██║  ██║  ██╗  ╚══╝  ██║   ██║██╔╚██╗ ██╔══██║██╔═══╝ ██╔══██║  
██████╔╝  ██║        ╚██████╔╝██║ ╚██╗██║  ██║██║     ██║  ██║
╚═════╝   ╚═╝         ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝

      DSB-induced Genome-wide Repair Analysis 
     and Profiling of Homologous recombination
                   ${VERSION}
 ${AUTHORS}
=============================================================

Description:
This tool performs genome-wide analysis of DNA repair following an HO-induced break. 
Di-GRAPH integrates:
  - MAT repair profiling
  - Genome instability evaluation based on coverage 
  - Recombination analysis based on inter-chromosomal discordant reads
Input files are gzipped paired-end fastq files.

OBLIGATORY OPTIONS:
    -b/--blast          Path to BLAST genomic database for cross-validation directory (provided in GitHub)
    -c/--categories     Path to genomic categories and features annotation directory (provided in GitHub)
    -g/--genome         Path to reference genome directory (provided in GitHub)
    -i/--input          Path to input directory (working directory generated by the user)
    -r/--report         Path to report directory (provided in GitHub)
    -S/--scripts        Path to scripts directory (provided in GitHub)


OTHER OPTIONS:
    -h/--help           Shows this help
    -s/--strain_ref     Name of the strain to be used as a reference (example: 1_Wt)
    -n/--number_exp     Number of experiments (default=3)
    -t/--threads        Number of threads to use (default=${N_CPU})
    -v/--version        Show version

EOF
}

if [ $# == 0 ]; then
	usage
	exit 1
fi

# VARIABLE OPTIONS

POSITIONAL=()
while [[ $# -gt 0 ]]
do
ARGS="$1"

case $ARGS in
    -b|--blast)
    if [ "$2" ]; then
        MYBLAST=$2
        shift 2
        if [ ! -d "${MYBLAST}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYBLAST})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-b/--blast" requires an argument\n'
        exit 1
    fi
    ;;
    -c|--categories)
    if [ "$2" ]; then
        CATEGORY_PATH=$2
        shift 2
        if [ ! -d "${CATEGORY_PATH}" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${CATEGORY_PATH})" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-c/--categories" requires an argument\n'
        exit 1
    fi
    ;;
    -i|--input)
    if [ "$2" ]; then
        MYWD=$2
        shift 2
        if [ ! -d "${MYWD}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYWD})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-i/--input" requires an argument\n'
        exit 1
    fi
    ;;
    -g|--genome)
    if [ "$2" ]; then
        MYREF=$2
        shift 2
        if [ ! -d "${MYREF}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREF})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-g/--genome" requires an argument\n'
        exit 1
    fi
    ;;
    -r|--report)
    if [ "$2" ]; then
        MYREPORT=$2
        shift 2
        if [ ! -d "${MYREPORT}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREPORT})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -S|--scripts)
    if [ "$2" ]; then
        MYSCRIPTS=$2
        shift 2
        if [ ! -d "${MYSCRIPTS}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYSCRIPTS})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-R/--Rscripts" requires an argument\n'
        exit 1
    fi
    ;;
    -s|--strain_ref)
    if [ "$2" ]; then
        STRAIN_REF=$2
        #echo STRAIN_REF=$STRAIN_REF
        shift 2
        if [[ ! -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_red}ERROR: ${STRAIN_REF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [[ -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_cyan}REFERENCE STRAIN: ${STRAIN_REF} will be used as reference strain!${COL_RESET} \n"
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -n|--number_exp)
    if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NUMBER_EXP=$2
            shift 2
        else
            echo -e '\nERROR: "-n/--number_exp" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-n/--number_exp" requires a numeric argument\n'
        exit 1
    fi
    ;;
    -t|--threads)
	if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NCPUS=$2
            shift 2
        else
            echo -e '\nERROR: "-t/--threads" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-t/--threads" requires a numeric argument\n'
        exit 1
    fi
	;;
    -v|--version)
        echo "${COL_yellow}Di-GRAPH version ${VERSION}${COL_RESET}"
        exit 1
    ;;
    -h|--help)
	    usage
	    exit 1
	;;
    -?*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
	    exit 1
	;;
	*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
        exit 1
    ;;
esac
done
set -- "${POSITIONAL[@]}" #restore positional parameters


REQUIRED_VARS=(MYBLAST CATEGORY_PATH MYWD MYREF MYREPORT MYSCRIPTS)
REQUIRED_OPTS=(
  "-b/--blast"
  "-c/--categories"
  "-i/--input"
  "-g/--genome"
  "-r/--report"
  "-S/--scripts"
)

missing=0

for i in "${!REQUIRED_VARS[@]}"; do
    var="${REQUIRED_VARS[$i]}"
    opt="${REQUIRED_OPTS[$i]}"

    if [ -z "${!var}" ]; then
        echo -e "${COL_red}ERROR:${COL_RESET} Required option $opt is missing"
        missing=1
    fi
done

if [ "$missing" -eq 1 ]; then
    usage
    exit 1
fi

if [[ "$STRAIN_REF" == "no" ]]; then
    echo -e "\n${COL_blue}REFERENCE STRAIN: no reference strain will be used${COL_RESET} \n"
fi

if [[ "$NUMBER_EXP" != 3 ]]; then
    echo -e "\n${COL_blue}NUMBER OF EXPERIMENTS: $NUMBER_EXP experiments will be analyzed${COL_RESET} \n"
fi

read -rp "Please, enter experiment names (comma-separated, e.g. E1,E3,E4): " NAME_EXP

IFS=',' read -ra EXP_LIST <<< "$NAME_EXP"


if [ "${#EXP_LIST[@]}" -ne "$NUMBER_EXP" ]; then
    echo "ERROR: You specified $NUMBER_EXP experiments but provided ${#EXP_LIST[@]} names."
    exit 1
fi

current_time=$(date "+%d-%m-%Y %H:%M:%S")
log_file="${MYWD}/log_file2.txt"
stats="${MYWD}/stats2.txt"

##### Radar plot TSG,TLG,TLR same plot
#R_SCRIPT="DISC_calculate_radar_perc_levels.R"
R_SCRIPT="DISC_calculate_radar_perc_levels.R"
# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
  for blast_option in option1 option2 option3 option4 option5 ; do
    echo "Processing directory: ${strain}" >> "$log_file"
    root_dir="${strain}"
    wd_dir="${MYWD}"
    strain="${strain}"
    blast_option="${blast_option}"

    echo "$(basename "$strain")" >> "$log_file"
    echo "" >> "$log_file"  # Adds a blank line
    echo "Calculating radar plot for $blast_option" >> "$log_file"
    start_time=$SECONDS
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain" "$wd_dir" "$blast_option"; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain} ${blast_option}" >> "$log_file"
        echo "Skipping ${strain} ${blast_option} and continuing..." >> "$log_file"
        continue
    fi 
    elapsed_time=$((( SECONDS - start_time )))
    echo "Total R processing completed in ${elapsed_time} seconds" >> "$log_file"
    echo "" >> "$log_file"  # Adds a blank line   
  done
done


##### Radar plots TSG, TLG and TLR (read_number)
#R_SCRIPT="DISC_calculate_radar_number_levels.R"
R_SCRIPT="DISC_calculate_radar_number_levels_onlyTSG.R"
# Loop inside each subdirectory of MYWD
for strain in "${MYWD}"*/; do
    echo "Processing directory: ${strain}" >> "$log_file"
    root_dir="${strain}"
    wd_dir="${MYWD}"
    strain="${strain}"
    echo "$(basename "$strain")" >> "$log_file"
    echo "" >> "$log_file"  # Adds a blank line
    echo "Plotting radar plots TSG, TLG and TLR - all blast options..." >> "$log_file"
    start_time=$SECONDS
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain" "$wd_dir"; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
        echo "Skipping ${strain} and continuing..." >> "$log_file"
        continue
    fi                
    # Calculate elapsed time
    elapsed_time=$((( SECONDS - start_time )))
    echo "Total R processing completed in ${elapsed_time} seconds" >> "$log_file"
    echo "" >> "$log_file"  # Adds a blank line 
done

mv "${subdir}"/*_inter_discordant_pairs_unique_processed_valid_counts.tsv  "${subdir}/Discordant_global_analysis/Global_Data_75nt/" 2> /dev/null
mv "${subdir}"/Radar_plot_*.svg  "${subdir}/Discordant_global_analysis/Global_Plots_75nt/" 2> /dev/null

##### REPORT GENERATION #####

# Generate report file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Generating report file at: \"$current_time\"" 

# Paths
RMD_FILE="Di-GRAPH_report.Rmd"
R_SCRIPT="generate_report.R"

# Copy Rmd to folder2
cp "${MYREPORT}/${RMD_FILE}" "${MYWD}/"

# Move into folder2
cd "${MYWD}"

# Run R script
Rscript "${MYREPORT}/${R_SCRIPT}"

# Remove copied Rmd after successful render
rm "${RMD_FILE}"
