#!/bin/bash

AUTHORS="Lydia Iglesias, Narciso M. Quijada, Andrés Clemente-Blanco"
LASTMODIF="2026-04-23"
VERSION="0.3.2"
MODIFICATIONS="experiment name dynamically set, SR"


DiGRAPH=$0
while [ -h "$DiGRAPH" ]; do # resolve $DiGRAPH until the file is no longer a symlink
  DiGRAPHDIR="$( cd -P "$( dirname "$0" )" && pwd )"
  DiGRAPH="$(readlink "$DiGRAPH")"
  [[ $DiGRAPH != /* ]] && DiGRAPH="$DiGRAPHDIR/$DiGRAPH" # if $DiGRAPH is a symlink, resolve it relative to the path where the symlink file was located
done
DiGRAPHDIR="$( cd -P "$( dirname "$DiGRAPH" )" && pwd )"

# WORKING VARIABLES
CATEGORY_PATH=
MYBLAST=
MYREF=
MYREPORT=
MYWD=
MYSCRIPTS=
STRAIN_REF="no"
NUMBER_EXP=3
N_CPU=$(nproc)
#N_CPU=$(sysctl -n hw.ncpu) #macOS

current_time=
log_file=
stats=

#MYREF=/home/ibfg/GWSL/RG # Replace with the path to your MYREF directory: path/to/RG
#MYWD=/home/ibfg/GWSL/WD/ # Replace with the path to your MYWD directory: path/to/WD
#CATEGORY_PATH=/home/ibfg/GWSL/Categories # Replace with the path to your CATEGORY_PATH directory: path/to/Categories
#MYBLAST=/home/ibfg/GWSL/BLAST/features_extraction # Replace with the path to your MYBLAST directory: path/to/BLAST/features_extraction
#MYREPORT=/home/ibfg/GWSL/Report_files # Replace with the path to your MYREPORT directory: path/to/Report_files

# Message colors
COL_RESET=$(tput sgr 0)
COL_blue=$(tput setaf 4)
COL_cyan=$(tput setaf 6)
COL_green=$(tput setaf 2)
COL_magenta=$(tput setaf 5)
COL_purple=$(tput setaf 5)
COL_red=$(tput setaf 1)
COL_white=$(tput setaf 7)
COL_yellow=$(tput setaf 3)

usage () {

cat << EOF

=============================================================

██████╗               ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗
██╔══██╗  ██╗        ██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║
██║  ██║  ╚═╝  ███╗  ██║  ███╗██████╔╝███████║██████╔╝███████║  
██║  ██║  ██╗  ╚══╝  ██║   ██║██╔╚██╗ ██╔══██║██╔═══╝ ██╔══██║  
██████╔╝  ██║        ╚██████╔╝██║ ╚██╗██║  ██║██║     ██║  ██║
╚═════╝   ╚═╝         ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝

      DSB-induced Genome-wide Repair Analysis 
     and Profiling of Homologous recombination
                   ${VERSION}
 ${AUTHORS}
=============================================================

Description:
This tool performs genome-wide analysis of DNA repair following an HO-induced break. 
Di-GRAPH integrates:
  - MAT repair profiling
  - Genome instability evaluation based on coverage 
  - Recombination analysis based on inter-chromosomal discordant reads
Input files are gzipped paired-end fastq files.

OBLIGATORY OPTIONS:
    -b/--blast          Path to BLAST genomic database for cross-validation directory (provided in GitHub)
    -c/--categories     Path to genomic categories and features annotation directory (provided in GitHub)
    -g/--genome         Path to reference genome directory (provided in GitHub)
    -i/--input          Path to input directory (working directory generated by the user)
    -r/--report         Path to report directory (provided in GitHub)
    -S/--scripts        Path to scripts directory (provided in GitHub)


OTHER OPTIONS:
    -h/--help           Shows this help
    -s/--strain_ref     Name of the strain to be used as a reference (example: 1_Wt)
    -n/--number_exp     Number of experiments (default=3)
    -t/--threads        Number of threads to use (default=${N_CPU})
    -v/--version        Show version

EOF
}

if [ $# == 0 ]; then
	usage
	exit 1
fi

# VARIABLE OPTIONS

POSITIONAL=()
while [[ $# -gt 0 ]]
do
ARGS="$1"

case $ARGS in
    -b|--blast)
    if [ "$2" ]; then
        MYBLAST=$2
        shift 2
        if [ ! -d "${MYBLAST}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYBLAST})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYBLAST} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-b/--blast" requires an argument\n'
        exit 1
    fi
    ;;
    -c|--categories)
    if [ "$2" ]; then
        CATEGORY_PATH=$2
        shift 2
        if [ ! -d "${CATEGORY_PATH}" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${CATEGORY_PATH})" ]; then
            echo -e "\n${COL_red}ERROR: ${CATEGORY_PATH} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-c/--categories" requires an argument\n'
        exit 1
    fi
    ;;
    -i|--input)
    if [ "$2" ]; then
        MYWD=$2
        shift 2
        if [ ! -d "${MYWD}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYWD})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYWD} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-i/--input" requires an argument\n'
        exit 1
    fi
    ;;
    -g|--genome)
    if [ "$2" ]; then
        MYREF=$2
        shift 2
        if [ ! -d "${MYREF}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREF})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREF} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-g/--genome" requires an argument\n'
        exit 1
    fi
    ;;
    -r|--report)
    if [ "$2" ]; then
        MYREPORT=$2
        shift 2
        if [ ! -d "${MYREPORT}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYREPORT})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYREPORT} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -S|--scripts)
    if [ "$2" ]; then
        MYSCRIPTS=$2
        shift 2
        if [ ! -d "${MYSCRIPTS}" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [ ! "$(ls -A ${MYSCRIPTS})" ]; then
            echo -e "\n${COL_red}ERROR: ${MYSCRIPTS} is empty!${COL_RESET} Please check \n"
            exit 1
        fi
    else
        echo -e '\nERROR: "-R/--Rscripts" requires an argument\n'
        exit 1
    fi
    ;;
    -s|--strain_ref)
    if [ "$2" ]; then
        STRAIN_REF=$2
        #echo STRAIN_REF=$STRAIN_REF
        shift 2
        if [[ ! -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_red}ERROR: ${STRAIN_REF} doesn't exist!${COL_RESET} Please check \n"
            exit 1
        fi
        if [[ -d "${MYWD}/$STRAIN_REF" ]]; then 
            echo -e "\n${COL_cyan}REFERENCE STRAIN: ${STRAIN_REF} will be used as reference strain!${COL_RESET} \n"
        fi
    else
        echo -e '\nERROR: "-r/--report" requires an argument\n'
        exit 1
    fi
    ;;
    -n|--number_exp)
    if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NUMBER_EXP=$2
            shift 2
        else
            echo -e '\nERROR: "-n/--number_exp" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-n/--number_exp" requires a numeric argument\n'
        exit 1
    fi
    ;;
    -t|--threads)
	if [ "$2" ]; then
		if [ "$2" -eq "$2"  ] 2>/dev/null ; then
            NCPUS=$2
            shift 2
        else
            echo -e '\nERROR: "-t/--threads" requires a numeric argument'
            echo -e "argument parsed: $2 \n"
            exit 1
        fi
	else
		echo -e '\nERROR: "-t/--threads" requires a numeric argument\n'
        exit 1
    fi
	;;
    -v|--version)
        echo "${COL_yellow}Di-GRAPH version ${VERSION}${COL_RESET}"
        exit 1
    ;;
    -h|--help)
	    usage
	    exit 1
	;;
    -?*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
	    exit 1
	;;
	*)
	    usage
        echo -e "\n${COL_red}ERROR: unknown option: ${1}${COL_RESET}\n"
        exit 1
    ;;
esac
done
set -- "${POSITIONAL[@]}" #restore positional parameters


REQUIRED_VARS=(MYBLAST CATEGORY_PATH MYWD MYREF MYREPORT MYSCRIPTS)
REQUIRED_OPTS=(
  "-b/--blast"
  "-c/--categories"
  "-i/--input"
  "-g/--genome"
  "-r/--report"
  "-S/--scripts"
)

missing=0

for i in "${!REQUIRED_VARS[@]}"; do
    var="${REQUIRED_VARS[$i]}"
    opt="${REQUIRED_OPTS[$i]}"

    if [ -z "${!var}" ]; then
        echo -e "${COL_red}ERROR:${COL_RESET} Required option $opt is missing"
        missing=1
    fi
done

if [ "$missing" -eq 1 ]; then
    usage
    exit 1
fi

if [[ "$STRAIN_REF" == "no" ]]; then
    echo -e "\n${COL_blue}REFERENCE STRAIN: no reference strain will be used${COL_RESET} \n"
fi

if [[ "$NUMBER_EXP" != 3 ]]; then
    echo -e "\n${COL_blue}NUMBER OF EXPERIMENTS: $NUMBER_EXP experiments will be analyzed${COL_RESET} \n"
fi

read -rp "Please, enter experiment names (comma-separated, e.g. E1,E3,E4): " NAME_EXP

IFS=',' read -ra EXP_LIST <<< "$NAME_EXP"


if [ "${#EXP_LIST[@]}" -ne "$NUMBER_EXP" ]; then
    echo "ERROR: You specified $NUMBER_EXP experiments but provided ${#EXP_LIST[@]} names."
    exit 1
fi
#echo "Working"
#################################

######## Starting the analysis ########
# Create a log and stat file
current_time=$(date "+%d-%m-%Y %H:%M:%S")
log_file="${MYWD}/log_file.txt"
stats="${MYWD}/stats.txt"

# Start timer for the entire script processing
start_time_total_script=$SECONDS

echo "CONCORDANT ANALYSIS - initiated at: \"$current_time\"" > "$log_file"
echo "" >> "$log_file"  # Adds a blank line

echo "=========  Bowtie Alignment ==========" >> "$stats"


# Index RG
bowtie-build "${MYREF}/RG_PMV_v9.fasta" "${MYREF}/S_cerevisiae_indexed" #NMQ --> MOVE TO INSTALL!


###########################################
### COVERAGE AND POLYMORPHISMS ANALYSIS ###
###########################################

echo "Coverage and Polymorphisms Analysis - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line

# Start timers for Coverage and Polymorphism Analysis processing

start_time_total_cov=$SECONDS

# Loop through each directory inside MYWD
for subdir in "$MYWD"*/; do
  echo "Processing directory: $subdir" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    for sample in T0 TSG TLG TLR; do
      for experiment in "${EXP_LIST[@]}"; do
        file1_gz="${subdir}/${sample}_${experiment}_R1.fastq.gz"
        file2_gz="${subdir}/${sample}_${experiment}_R2.fastq.gz"
       
        # Check if both compressed files exist
        if [[ -f "$file1_gz" && -f "$file2_gz" ]]; then
          echo "Processing files: $file1_gz, $file2_gz" >> "$log_file"
          echo "" >> "$log_file"  # Adds a blank line

          # Decompress the current pair
          gunzip -k "$file1_gz" "$file2_gz"
          file1_path="${subdir}/${sample}_${experiment}_R1.fastq"
          file2_path="${subdir}/${sample}_${experiment}_R2.fastq"
          
          # Concatenate the two fastq files
          cat "$file1_path" "$file2_path" > "${subdir}/${sample}_${experiment}.fastq"
                
          # Remove original fastq files
          rm "$file1_path" "$file2_path"

          if [[ -f "${subdir}/${sample}_${experiment}.fastq" ]]; then
    
            # Trim reads using cutadapt
            cutadapt -j "$N_CPU" --cut -75 -o "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}.fastq"
            cutadapt -j "$N_CPU" --cut 75 -o "${subdir}/${sample}_${experiment}_2.fastq" "${subdir}/${sample}_${experiment}.fastq"
                    
            # Cut 38nt from the beginning and 38nt from the end
            cutadapt -j "$N_CPU" --cut -38 -o "${subdir}/${sample}_${experiment}_1_1.fastq" "${subdir}/${sample}_${experiment}_1.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${subdir}/${sample}_${experiment}_1_2.fastq" "${subdir}/${sample}_${experiment}_1.fastq"
            cutadapt -j "$N_CPU" --cut -38 -o "${subdir}/${sample}_${experiment}_2_1.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            cutadapt -j "$N_CPU" --cut 38 -o "${subdir}/${sample}_${experiment}_2_2.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            
            # Cut 19nt from the beginning and 19nt from the end
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_1_1_1.fastq" "${subdir}/${sample}_${experiment}_1_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_1_1_2.fastq" "${subdir}/${sample}_${experiment}_1_1.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_1_2_1.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_1_2_2.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_2_1_1.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_2_1_2.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq"
            cutadapt -j "$N_CPU" --cut -19 -o "${subdir}/${sample}_${experiment}_18nts_2_2_1.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            cutadapt -j "$N_CPU" --cut 19 -o "${subdir}/${sample}_${experiment}_18nts_2_2_2.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            
            # Remove intermediate files
            rm "${subdir}/${sample}_${experiment}_1_1.fastq" "${subdir}/${sample}_${experiment}_1_2.fastq" "${subdir}/${sample}_${experiment}_2_1.fastq" "${subdir}/${sample}_${experiment}_2_2.fastq"
            
            # Catenate processed reads into a single fastq file
            cat "${subdir}/${sample}_${experiment}_18nts"*".fastq" > "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq"
            
                # Filter 18nt reads Q30
                fastp \
                  -i "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq" \
                  -o "${subdir}/${sample}_${experiment}_18nt.fastq" \
                  -q 30 -u 0 -e 30 \
                  --thread "$N_CPU" \
                  --html "${subdir}/${sample}_${experiment}_18nt.fastq.html" \
                  --json "${subdir}/${sample}_${experiment}_18nt.fastq.json" 
                rm "${subdir}/${sample}_${experiment}_18nt_nonfiltered.fastq" # Remove intermediate 18nt fastq files
            
            # Remove intermediate 18nt fastq files
            rm "${subdir}/${sample}_${experiment}_18nts"*".fastq"

            # Remove intermediate fastq files
            rm "${subdir}/${sample}_${experiment}.fastq"

            # Concatenate processed 75nt reads into a single fastq file
            cat "${subdir}/${sample}_${experiment}_1.fastq" \
                "${subdir}/${sample}_${experiment}_2.fastq" \
              > "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq"
                    
                # Filter 75nt reads Q30
                fastp \
                  -i "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" \
                  -o "${subdir}/${sample}_${experiment}_75nt.fastq" \
                  -q 30 -u 0 -e 30 \
                  --thread "$N_CPU" \
                  --html "${subdir}/${sample}_${experiment}_75nt.fastq.html" \
                  --json "${subdir}/${sample}_${experiment}_75nt.fastq.json"
                rm "${subdir}/${sample}_${experiment}_75nt_nonfiltered.fastq" # Remove intermediate 75nt fastq files
                
            # Remove intermediate 75nt fastq files
            rm "${subdir}/${sample}_${experiment}_1.fastq" "${subdir}/${sample}_${experiment}_2.fastq"
            
            # Bowtie mapping
            echo "### $(basename "$subdir")/${sample}/${experiment} 75nt ###" >> "$stats"
            bowtie -p "$N_CPU" -m 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed" "${subdir}/${sample}_${experiment}_75nt.fastq" > "${subdir}/${sample}_${experiment}_75nt.sam" 2>> "$stats"
            echo "" >> "$stats"
                    
            # Aligning using 18nt reads, in -k mode
            echo "### $(basename "$subdir")/${sample}/${experiment} 18nt ###" >> "$stats"
            bowtie -p "$N_CPU" -k 1 -v 0 -S -x "${MYREF}/S_cerevisiae_indexed" "${subdir}/${sample}_${experiment}_18nt.fastq" > "${subdir}/${sample}_${experiment}_18nt.sam" 2>> "$stats"
            echo "" >> "$stats"

            # Convert SAM to sorted BAM (75nt)
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.sam"
            samtools index "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.bai"
                    
            # Convert SAM to sorted BAM (18nt)
            samtools sort -@ "$N_CPU" -o "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.sam"
            samtools index "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.bai"
                    
            # Generate BedGraphs coverage files (75nt)
            bamCoverage -b "${subdir}/${sample}_${experiment}_75nt.bam" -o "${subdir}/${sample}_${experiment}_75nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230

            # Sorting Bedgraphs files (75nt)
            samtools faidx "${MYREF}/RG_PMV_v9.fasta" # Create index file
            cut -f1,2 "${MYREF}/RG_PMV_v9.fasta.fai" > "${MYREF}/chrom_order.txt"
            bedtools sort -i "${subdir}/${sample}_${experiment}_75nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_75nt_sorted.bedgraph"
                    
            # Generate BedGraphs coverage files (18nt)
            bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRIII_18nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230 -r CHRIII:199953:201553
            bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRV_18nt.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --normalizeUsing RPGC --effectiveGenomeSize 14272230 -r CHRV:289025:290625

            # Sorting Bedgraphs files (18nt)            
            bedtools sort -i "${subdir}/${sample}_${experiment}_CHRIII_18nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_sorted.bedgraph"
            bedtools sort -i "${subdir}/${sample}_${experiment}_CHRV_18nt.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRV_18nt_sorted.bedgraph"

            # For TSG, TLG and TLR, generate BedGraphs coverage files (18nt) nonRPGC for quantifications
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --effectiveGenomeSize 14272230 -r CHRIII:199953:201553
              bamCoverage -b "${subdir}/${sample}_${experiment}_18nt.bam" -o "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.bedgraph" -of bedgraph -p "$N_CPU" -bs 1 --effectiveGenomeSize 14272230 -r CHRV:289025:290625

              # Sorting Bedgraphs files (18nt_nonRPGC)
              bedtools sort -i "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.bedgraph" -g "${MYREF}/chrom_order.txt" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_sorted.bedgraph"
              bedtools sort -i "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.bedgraph" -g "${MYREF}/chrom_order.txt"> "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_sorted.bedgraph"
            fi

            # Generate TSV files (75nt)
            bedtools coverage -a "${subdir}/${sample}_${experiment}_75nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_75nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_75nt.tsv"
            
            # Generate TSV files (18nt)
            bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRIII_18nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv"
            bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRV_18nt_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv"

            # For TSG, TLG and TLR, generate TSV files (18nt) nonRPGC for quantifications
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv"
              bedtools coverage -a "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_sorted.bedgraph" -b "${subdir}/${sample}_${experiment}_18nt.bam" -sorted -g "${MYREF}/chrom_order.txt" -d > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv"
            fi
                    
            # Reduced decimals in coverage column (4th) (75nt) # Link this file for next blocks!!
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_75nt.tsv" > "${subdir}/${sample}_${experiment}_75nt.tmp" && mv "${subdir}/${sample}_${experiment}_75nt.tmp" "${subdir}/${sample}_${experiment}_75nt.tsv" # Linking file for next blocks!!!

            # Reduced decimals in coverage column (4th) (18nt)
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt.tmp" && mv "${subdir}/${sample}_${experiment}_CHRIII_18nt.tmp" "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv"
            awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt.tmp" && mv "${subdir}/${sample}_${experiment}_CHRV_18nt.tmp" "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv"
            
            # For TSG, TLG and TLR reduced decimals in coverage column (4th) nonRPGC for quantifications
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tmp" && mv "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tmp" "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv"
              awk -F'\t' 'BEGIN{OFS=FS} {split($4,a,"."); if(length(a)>1) $4=a[1]"."substr(a[2],1,5); print}' "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tmp" && mv "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tmp" "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv"
            fi

            # Extract CHRIII and CHRV, remove columnes 2, 3, 5, 6, and add coordinates to the last column (75nt)
            for chr in CHRIII CHRV; do
              awk -F'\t' -v chr="$chr" '$1 == chr {print $1, $4}' OFS='\t' "${subdir}/${sample}_${experiment}_75nt.tsv" | awk 'BEGIN {OFS="\t"} {print $0, NR}' > "${subdir}/${sample}_${experiment}_75nt_${chr}.tsv"
                        
              # Extract MATs
              if [[ $chr == "CHRIII" ]]; then
                awk -F'\t' '$3 >= 199953 && $3 <= 201553' "${subdir}/${sample}_${experiment}_75nt_CHRIII.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRIII_MATa.tsv"
              elif [[ $chr == "CHRV" ]]; then
                awk -F'\t' '$3 >= 289025 && $3 <= 290625' "${subdir}/${sample}_${experiment}_75nt_CHRV.tsv" > "${subdir}/${sample}_${experiment}_75nt_CHRV_MATa.tsv"
              fi
            done

            # Remove columnes 2, 3, 5, 6, and add coordinates to the last column (18nt)

            awk -F'\t' 'BEGIN {OFS="\t"} {coord=199953+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRIII_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_ordered.tsv"
            awk -F'\t' 'BEGIN {OFS="\t"} {coord=289025+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRV_18nt.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_ordered.tsv"

            # For TSG, TLG and TLR, remove columnes 2, 3, 5, 6, and add coordinates to the last column (nonRPGC for quantifications)
            if [[ "$sample" == "TSG" || "$sample" == "TLG" || "$sample" == "TLR" ]]; then
              awk -F'\t' 'BEGIN {OFS="\t"} {coord=199953+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRIII_18nt_nonRPGC_ordered.tsv"
              awk -F'\t' 'BEGIN {OFS="\t"} {coord=289025+NR-1; print $1, $4, coord}' "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC.tsv" > "${subdir}/${sample}_${experiment}_CHRV_18nt_nonRPGC_ordered.tsv"
            fi
                    
            # Clean intermediate files
            rm "${subdir}/${sample}_${experiment}_75nt.fastq" "${subdir}/${sample}_${experiment}_75nt.bam" "${subdir}/${sample}_${experiment}_75nt.bai" "${subdir}/${sample}_${experiment}_75nt.sam"
            rm "${subdir}/${sample}_${experiment}_18nt.fastq" "${subdir}/${sample}_${experiment}_18nt.bam" "${subdir}/${sample}_${experiment}_18nt.bai" "${subdir}/${sample}_${experiment}_18nt.sam"

          else
          echo "Warning: Decompressed files missing for sample $sample in $subdir!" >> "$log_file"
          echo "" >> "$log_file"
          fi
        else
        echo "Warning: One or both compressed files for sample $sample are missing in $subdir!" >> "$log_file"
        echo "" >> "$log_file"
        fi
      done
    done
done




for strain in "$MYWD"*/; do
  echo "Processing directory: $strain to calculate average coverage" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line

  # Loop through sample prefixes (T0, T1, T2, etc.)
    R_SCRIPT="SR_process_cov_III_V.R"
    strain="${strain}"
    root_dir="${strain}"
    echo "Processing strain: $strain" >> "$log_file"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
          continue
        fi  
done




### === DATA ORGANIZATION ===

#Crate folder for the Alignment output files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Alignment_data"
    mv "${subdir}"/*.bedgraph "${subdir}/Alignment_data/"
done

# Create a folder for the Coverage TSV files
for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/Coverage_data"
    mv "${subdir}"/*_Coverage.tsv "${subdir}/Coverage_data/"
done

for subdir in "${MYWD}"*/; do
    mkdir -p "${subdir}/MATs_quant_data"
    for chr in CHRIII CHRV; do
        mv "${subdir}"/*_"${chr}"_18nt_nonRPGC_ordered.tsv "${subdir}/MATs_quant_data/"
    done
done

# Create a folder for the graphs
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/Graphs_Coverage"
  mv "${subdir}/plot_"*".svg" "${subdir}/Graphs_Coverage/"
done

# Create a folder for FASTQP files
for subdir in "$MYWD"*/; do
  mkdir -p "${subdir}/FASTQP"
  mv "${subdir}"/*.fastq.html "${subdir}/FASTQP/"
  mv "${subdir}"/*.fastq.json "${subdir}/FASTQP/"
done

# Remove index files
find "$MYREF" -name "*.ebwt" -exec rm {} +
find "$MYREF" -name "*.fai" -exec rm {} +
find "$MYREF" -name "*.txt" -exec rm {} +

#Delete all TSV files in subdir, excluding those in Alignment_data
for subdir in "${MYWD}"*; do
    find "${subdir}" -maxdepth 1 -type f -name "*.tsv" ! -name "*_75nt.tsv" -exec rm {} \;
done



### === MATs quantification for TSG, TLG and TLR ===
# This section calculates the difference in coverage for polymorphism between CHRIII and CHRV

# Coordinates (you can add more coordinates separated by space)
coordinates_CHRIII=(200119 200167 200212 200272 200326 200386 200449 200509 200542 200575 200635 200689 200753 200817 200882 200947 201012 201077 201148 201207 201272 201337 201402)
coordinates_CHRV=(289191 289239 289284 289344 289398 289458 289521 289581 289614 289647 289707 289761 289825 289889 289954 290019 290084 290149 290220 290278 290343 290408 290473)

offset=19 

for subdir in "$MYWD"*/MATs_quant_data/; do
  for sample in TSG TLG TLR; do
    for exp in "${EXP_LIST[@]}"; do
      input_file_CHRIII="${subdir}/${sample}_${exp}_CHRIII_18nt_nonRPGC_ordered.tsv"
      input_file_CHRV="${subdir}/${sample}_${exp}_CHRV_18nt_nonRPGC_ordered.tsv"

      if [[ -f "$input_file_CHRIII" && -f "$input_file_CHRV" ]]; then
        echo "Processing files in $subdir for $sample _ $exp..."

        # Loop through CHRIII coordinates
        for coordinate_CHRIII in "${coordinates_CHRIII[@]}"; do
          line_number_CHRIII=$(awk -v coord="$coordinate_CHRIII" '$3 == coord {print NR}' "$input_file_CHRIII")

          if [[ -n "$line_number_CHRIII" ]]; then
            top_line_CHRIII=$((line_number_CHRIII - offset))
            bottom_line_CHRIII=$((line_number_CHRIII + offset))
            [[ "$top_line_CHRIII" -lt 1 ]] && top_line_CHRIII=1

            top_line_content=$(sed -n "${top_line_CHRIII}p" "$input_file_CHRIII")
            mid_line_content=$(sed -n "${line_number_CHRIII}p" "$input_file_CHRIII")
            bottom_line_content=$(sed -n "${bottom_line_CHRIII}p" "$input_file_CHRIII")

            top_coverage=$(echo "$top_line_content" | awk '{print $2}')
            bottom_coverage=$(echo "$bottom_line_content" | awk '{print $2}')
            baseline_coverage=$(awk -v top="$top_coverage" -v bottom="$bottom_coverage" 'BEGIN {print top + (bottom - top)/2}')

            # Extract fields from mid_line_content
            mid_chr=$(echo "$mid_line_content" | awk '{print $1}')
            mid_coverage=$(echo "$mid_line_content" | awk '{print $2}')
            mid_coordinate=$(echo "$mid_line_content" | awk '{print $3}')

            # Calculate coverage difference (mid - baseline)
            coverage_diff=$(awk -v mid="$mid_coverage" -v base="$baseline_coverage" 'BEGIN {print mid - base}')

            # Build new line with: original chr, diff coverage, and coordinate (tab-separated)
            diff_line=$(echo -e "$mid_chr\t$coverage_diff\t$mid_coordinate")

            echo "CHRIII Coord: $coordinate_CHRIII — Coverage Diff: $coverage_diff"

            output_file_CHRIII="${subdir}/${sample}_${exp}_CHRIII_diff_${coordinate_CHRIII}.tsv"
            {
              echo "$diff_line"
            } > "$output_file_CHRIII"

          else
          echo "Coordinate $coordinate_CHRIII not found in $input_file_CHRIII for $sample $exp."
          fi
        done
    
        # Loop through CHRV coordinates
        for coordinate_CHRV in "${coordinates_CHRV[@]}"; do
          line_number_CHRV=$(awk -v coord="$coordinate_CHRV" '$3 == coord {print NR}' "$input_file_CHRV")

          if [[ -n "$line_number_CHRV" ]]; then
            top_line_CHRV=$((line_number_CHRV - offset))
            bottom_line_CHRV=$((line_number_CHRV + offset))
            [[ "$top_line_CHRV" -lt 1 ]] && top_line_CHRV=1

            top_line_content=$(sed -n "${top_line_CHRV}p" "$input_file_CHRV")
            mid_line_content=$(sed -n "${line_number_CHRV}p" "$input_file_CHRV")
            bottom_line_content=$(sed -n "${bottom_line_CHRV}p" "$input_file_CHRV")

            top_coverage=$(echo "$top_line_content" | awk '{print $2}')
            bottom_coverage=$(echo "$bottom_line_content" | awk '{print $2}')
            baseline_coverage=$(awk -v top="$top_coverage" -v bottom="$bottom_coverage" 'BEGIN {print top + (bottom - top)/2}')

            # Extract fields from mid_line_content
            mid_chr=$(echo "$mid_line_content" | awk '{print $1}')
            mid_coverage=$(echo "$mid_line_content" | awk '{print $2}')
            mid_coordinate=$(echo "$mid_line_content" | awk '{print $3}')

            # Calculate coverage difference (mid - baseline)
            coverage_diff=$(awk -v mid="$mid_coverage" -v base="$baseline_coverage" 'BEGIN {print mid - base}')

            # Build new line with: original chr, diff coverage, and coordinate (tab-separated)
            diff_line=$(echo -e "$mid_chr\t$coverage_diff\t$mid_coordinate")

            echo "CHRV Coord: $coordinate_CHRV — Coverage Diff: $coverage_diff"

            output_file_CHRV="${subdir}/${sample}_${exp}_CHRV_diff_${coordinate_CHRV}.tsv"
            {
              echo "$diff_line"
            } > "$output_file_CHRV"

          else
          echo "Coordinate $coordinate_CHRV not found in $input_file_CHRV for $sample $exp."
          fi
        done
      else
      echo "Files not found for $sample $exp in $subdir"
      fi
    done
  done
done


for strain in "$MYWD"*/; do
  echo "Processing directory: $strain to calculate MATa coverage (r18)" >> "$log_file"
  echo "" >> "$log_file"  # Adds a blank line
  strain="${strain}"
  root_dir="${strain}"

  # Loop through sample prefixes (T0, T1, T2, etc.)
    R_SCRIPT="SR_process_cov_III_V_18nt.R"
    strain="${strain}"
    root_dir="${strain}"
    echo "Processing strain: $strain" >> "$log_file"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
            echo "Skipping ${strain} and continuing..." >> "$log_file"
          continue
        fi  
done


# Move the plots to the Graphs_Coverage folder
for strain in "$MYWD"*/; do
  for sample in TSG TLG TLR; do
    mv "${strain}/plot_${sample}_18nt_MATa_Coverage_Quant.svg" "${strain}/Graphs_Coverage/"
  done
done

# Calulate total elapsed time
elapsed_time_total_cov=$((( SECONDS - start_time_total_cov )/60))
echo "Coverage and Polymorphisms Analysis completed in ${elapsed_time_total_cov} minutes" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line            


###########################################
####### GENOMIC CATEGORIES ANALYSIS #######
###########################################

current_time=$(date "+%d-%m-%Y %H:%M:%S")
echo "Genomic Categories Analysis - initiated at: \"$current_time\"" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line 

# Start timer for the R category analysis
start_time_total_cat=$SECONDS

# Loop through each directory inside MYWD
R_SCRIPT="SR_process_categories.R"
for strain in "$MYWD"*/; do
    for category in ORF LTR TEG Ty tRNA rRNA ncRNA snRNA snoRNA ARS Cen Tel Int; do
        echo "Processing category: $category" >> "$log_file"
        root_dir="${strain}"
        strain="${strain}"
        category="${category}"
        category_path="${CATEGORY_PATH}"

        if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain" "$category" "$category_path"; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain} and ${category}" >> "$log_file"
        echo "Skipping ${strain} and ${category} and continuing..." >> "$log_file"
        continue
    fi  

    done
done


### ORDERING CATEGORIES DATASET ###

# Loop through each directory inside MYWD
R_SCRIPT="SR_order_categories.R"
for strain in "${MYWD}"*/; do
  echo "Processing directory: $strain"
  for analysis_suffix in "T0vsTSG" "T0vsTLG" "T0vsTLR"; do
    echo "Processing analysis: $analysis_suffix"
    root_dir="${strain}"
    strain="${strain}"
    category_path="${CATEGORY_PATH}"
    analysis_suffix="${analysis_suffix}"

    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain" "$category_path" "$analysis_suffix"; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}, ${category} and ${analysis_suffix}" >> "$log_file"
    echo "Skipping ${strain}, ${category} and ${analysis_suffix} and continuing..." >> "$log_file"
    continue
    fi  
  done
done

# Move tsv category files into a category data folder
for strain in "${MYWD}"*/; do
  mkdir -p "${strain}/Category_Data_TSV_and_Plots"
  mv "${strain}"/*"fingerprint"* "${strain}/Category_Data_TSV_and_Plots/"
  #mv "${strain}"/*"all_data"* "${strain}/Category_Data_TSV_and_Plots/"
  mv "${strain}"/*".svg" "${strain}/Category_Data_TSV_and_Plots/"
done

### PLOTTING CATEGORIES DATA ###
 R_SCRIPT="SR_plot_categories.R"
for strain in "$MYWD"*/; do
  for analysis_suffix in "T0vsTSG" "T0vsTLG" "T0vsTLR"; do
    echo "Processing analysis: $analysis_suffix"
    root_dir="${strain}"
    strain="${strain}"
    analysis_suffix="${analysis_suffix}"
    echo "Processing time point: $analysis_suffix"
    if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain" "$analysis_suffix"; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain} and ${analysis_suffix}" >> "$log_file"
    echo "Skipping ${strain} and ${analysis_suffix} and continuing..." >> "$log_file"
    continue
    fi  

  done
done

# R plots for gal vs raf coverage
# Start timer for R processing

# Loop inside each subdirectory of MYWD
R_SCRIPT="SR_plot_gal_vs_raf.R"
for strain in "${MYWD}"*/; do
  echo "Processing directory: ${strain}" >> "$log_file"
      root_dir="${strain}"
      strain="${strain}"
        echo "$(basename "$strain")" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line
        echo "Plotting gal vs raf coverage" >> "$log_file"
        start_time=$SECONDS
        if ! Rscript "${MYSCRIPTS}/R_files/${R_SCRIPT}" "$root_dir" "$strain"; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR running R script for ${strain}" >> "$log_file"
        echo "Skipping ${strain} and continuing..." >> "$log_file"
        continue
        fi
      # Calculate elapsed time
        elapsed_time=$((( SECONDS - start_time )))
        echo "Total gal vs raf plotting completed in ${elapsed_time} seconds" >> "$log_file"
        echo "" >> "$log_file"  # Adds a blank line 

done


# Move tsv category files into a category data folder
for subdir in "${MYWD}"*/; do
  mkdir -p "${subdir}/Sorted_datasets"
  mv "${subdir}"/*"sorted"* "${subdir}/Sorted_datasets"
  mv "${subdir}"/*"Template"* "${subdir}/Sorted_datasets"
  mv "${subdir}"/*"UP_DOWN"* "${subdir}/Sorted_datasets"
  mv "${subdir}"/*".svg" "${subdir}/Plots_Analysis/"
done

# Move tsv files into a alignmentfolder
for subdir in "${MYWD}"*/; do
  mkdir -p "${subdir}/Alignment_data/TSV_files"
  mv "${subdir}"/*".tsv" "${subdir}/Alignment_data/TSV_files"
done

# Calulate total elapsed time
elapsed_time_total_cat=$((( SECONDS - start_time_total_cat )/60))
echo "Genomic Categories Analysis completed in ${elapsed_time_total_cat} minutes" >> "$log_file"
echo "" >> "$log_file"  # Adds a blank line
